// Step 5 native browser checks extending workflow.cjs. No mock DOM or audio clock.
const Test=require('./config.cjs'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const {chromium}=Test.dependency('playwright');
const near=(a,b)=>assert.ok(Math.abs(a-b)<.05,`${a} != ${b}`);
(async()=>{const b=await chromium.launch(Test.browserOptions());try{
 const context=await b.newContext({offline:true,acceptDownloads:true,viewport:{width:1440,height:1050}}),p=await context.newPage(),errors=[],requests=[],checks=[];
 p.on('pageerror',e=>errors.push(e.message));context.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});
 const field=async(id,value)=>{const el=p.locator('#'+id),d=el.locator('xpath=ancestor::details[not(@open)]');if(await d.count())await d.locator('summary').first().click();await el.fill(String(value));await el.press('Tab');};
 const kit=async id=>{await p.click('#kits-menu > summary');await p.click('#'+id);await p.waitForSelector('#import-dialog[open]');await p.click('#accept');await p.waitForFunction(()=>!SF.App.busy);};
 await p.goto(Test.htmlUrl);await kit('correction-demo');
 const clip=await p.evaluate(()=>SF.Studio.clipId);await p.click('#save');await p.waitForFunction(()=>!SF.App.busy&&!SF.Store.dirty);
 await field('correction-offsetX',76);await field('correction-offsetY',-14);
 assert.equal(await p.evaluate(()=>SF.Store.dirty),false);assert.equal(await p.evaluate(id=>SF.Corrections.track(SF.Store.project,id).keys.length,clip),0);
 await p.click('#correction-save');assert.equal(await p.evaluate(()=>SF.Store.dirty),true);
 await p.click('#correction-last');await field('correction-offsetX',-54);await field('correction-offsetY',-54);await field('correction-scalePercent',100/1.8);await p.click('#correction-save');
 await p.locator('#correction-frame').fill('5');await p.waitForTimeout(200);assert.equal(await p.locator('#correction-frame').inputValue(),'5');await p.locator('#correction-frame').press('Tab');near(Number(await p.locator('#correction-offsetX').inputValue()),76-130*5/11);
 const committed=Number(await p.locator('#correction-offsetX').inputValue());await field('correction-offsetX',500);await p.click('#correction-revert');near(Number(await p.locator('#correction-offsetX').inputValue()),committed);
 await p.click('#correction-original');near(await p.evaluate(id=>SF.Keyer.renderCorrection(id,5,'S',[1,1]).scale,clip),1);
 await p.click('#correction-corrected');assert.ok((await p.evaluate(id=>SF.Keyer.renderCorrection(id,5,'S',[1,1]).scale,clip))<1);
 checks.push('Native controls distinguish temporary drafts, committed keys, interpolation, revert and Original/Corrected preview');
 await p.click('#correction-first');const root=await p.evaluate(id=>SF.Placement.resolve(SF.Store.project,id),clip);
 await p.locator('#correction-drag').check();const box=await p.locator('#preview').boundingBox();assert.ok(box);
 await p.mouse.move(box.x+box.width/2,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+box.width/2+15,box.y+box.height/2-10);await p.mouse.up();
 assert.notEqual(Number(await p.locator('#correction-offsetX').inputValue()),76);assert.deepEqual(await p.evaluate(id=>SF.Placement.resolve(SF.Store.project,id),clip),root);
 await p.click('#correction-save');await p.click('#undo');near(await p.evaluate(id=>SF.Corrections.evaluate(SF.Store.project,id,0).offsetX,clip),76);
 await p.locator('#zoom').focus();await p.locator('#zoom').press('ArrowRight');assert.deepEqual(await p.evaluate(id=>SF.Placement.resolve(SF.Store.project,id),clip),root);
 checks.push('Actual pointer drag changes draft correction only; committed drag Undo restores keys; preview zoom preserves authored placement');
 await kit('action-demo');const actionClip=await p.evaluate(()=>SF.Studio.clipId);
 await p.click('[data-tab=ground]');await field('scalePercent',75);const shape=p.locator('#shapeLinked');if(!await shape.isVisible())await shape.locator('xpath=ancestor::details').locator('summary').click();await shape.uncheck();await field('widthPercent',140);await field('heightPercent',80);
 const mainPlacement=await p.evaluate(id=>SF.Placement.resolve(SF.Store.project,id),clip),actionPlacement=await p.evaluate(id=>SF.Placement.resolve(SF.Store.project,id),actionClip);
 assert.deepEqual(mainPlacement,root);near(actionPlacement.scalePercent,75);near(actionPlacement.widthPercent,140);near(actionPlacement.heightPercent,80);
 await p.click('#undo');near(await p.evaluate(id=>SF.Placement.resolve(SF.Store.project,id).heightPercent,actionClip),100);await p.click('#redo');
 checks.push('Actual extra-clip scale and unlinked width/height edits preserve main placement; Undo/Redo restore shape edits');
 await p.click('[data-tab=states]');await p.click('#state-test');await p.waitForFunction(()=>SF.App.playing);
 await p.click('#play');const elapsed=await p.evaluate(()=>SF.Studio.pose().elapsed);await p.waitForTimeout(200);near(await p.evaluate(()=>SF.Studio.pose().elapsed),elapsed);
 await p.click('#state-test');await p.waitForFunction(()=>SF.Studio.pose().phase==='return',null,{timeout:5000});
 await p.locator('#state-retrigger').selectOption('queue');await p.click('#state-test');await p.click('#state-test');assert.equal(await p.evaluate(()=>SF.Studio.pose().queued),true);
 await p.click('#play');assert.equal(await p.evaluate(()=>SF.App.playing),false);
 checks.push('Native action test completes once into return; Pause freezes elapsed time; Queue one and interruption controls work');
 await p.screenshot({path:Test.outputPath('acceptance.png'),fullPage:true});assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);
 fs.writeFileSync(Test.outputPath('acceptance-results.json'),JSON.stringify({browser:await b.version(),htmlSha256:crypto.createHash('sha256').update(fs.readFileSync(Test.projectPath('SpriteForge.html'))).digest('hex'),offline:true,checks,errors,requests,humanListening:false},null,2));console.log('PASS '+checks.join('\nPASS '));
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
