// Small generated fixtures exercise native browser codecs, not mock ImageDecoder.
const Test=require('./config.cjs'),fs=require('node:fs'),assert=require('node:assert/strict'),crypto=require('node:crypto'),JSZip=require('../vendor/jszip.min.js');
const sharp=Test.dependency('sharp'),{chromium}=Test.dependency('playwright');
(async()=>{const b=await chromium.launch(Test.browserOptions());try{
 const files=[],raw=Buffer.alloc(9*13*4);for(let i=0;i<raw.length;i+=4){raw[i]=231;raw[i+1]=188;raw[i+2]=114;raw[i+3]=i%36<8?0:255;}
 const base=sharp(raw,{raw:{width:9,height:13,channels:4}});
 for(const [name,bytes]of [['pose_1.jpeg',await base.clone().flatten({background:'#821415'}).jpeg().toBuffer()],['pose_2.png',await base.clone().png().toBuffer()],['pose_3.webp',await base.clone().webp({lossless:true}).toBuffer()],['pose_4.gif',await base.clone().gif().toBuffer()],['pose_5.svg',Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="5" height="7"><rect width="5" height="7" fill="gold"/></svg>')]]){const file=Test.outputPath(name);fs.writeFileSync(file,bytes);files.push(file);}
 const c=await b.newContext({offline:true,acceptDownloads:true}),p=await c.newPage(),errors=[],requests=[],checks=[];p.on('pageerror',e=>errors.push(e.message));c.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url());});await p.goto(Test.htmlUrl);
 await p.setInputFiles('#files',files.reverse());await p.waitForSelector('#import-dialog[open]');assert.equal(await p.locator('#accept').isDisabled(),true);await p.locator('#padding').check();await p.click('#accept');await p.waitForFunction(()=>!SF.App.busy);
 const imported=await p.evaluate(()=>({names:SF.Store.project.frames.map(f=>f.name),alpha:SF.Store.project.frames.map(f=>f.transparent),canvas:SF.Store.project.canvas,sizes:SF.Store.project.frames.map(f=>[f.width,f.height])}));assert.deepEqual(imported.names,['pose_1.jpeg','pose_2.png','pose_3.webp','pose_4.gif','pose_5.svg']);assert.equal(imported.alpha[0],false);assert.equal(imported.alpha[1],true);assert.deepEqual(imported.canvas,[9,13]);assert.deepEqual(imported.sizes[4],[5,7]);
 checks.push('Native JPEG/PNG/WebP/GIF/self-contained SVG imports preserve alpha, numeric order and mixed dimensions');
 const [saved]=await Promise.all([p.waitForEvent('download'),p.click('#save')]);const file=Test.outputPath('mixed.spriteforge.zip');await saved.saveAs(file);await p.waitForFunction(()=>!SF.App.busy);await p.setInputFiles('#project-file',file);await p.waitForFunction(()=>!SF.App.busy&&!SF.Store.dirty&&document.querySelector('#status').textContent.includes('reopened'));
 const [exported]=await Promise.all([p.waitForEvent('download'),p.click('#export')]);const packFile=Test.outputPath('mixed-source-pack.zip');await exported.saveAs(packFile);await p.waitForFunction(()=>!SF.App.busy);const zip=await JSZip.loadAsync(fs.readFileSync(packFile),{checkCRC32:true});const pngs=Object.values(zip.files).filter(f=>!f.dir&&f.name.includes('/S/')&&f.name.endsWith('.png'));assert.equal(pngs.length,5);for(const f of pngs){const metadata=await sharp(await f.async('nodebuffer')).metadata();assert.equal(metadata.width,9);assert.equal(metadata.height,13);}
 checks.push('Native mixed-format project reopens and exports CRC-valid PNG pack');
 const animRaw=Buffer.alloc(3*4*4*2);for(let i=0;i<animRaw.length;i+=4){animRaw[i]=i<48?255:0;animRaw[i+1]=i<48?0:255;animRaw[i+3]=i%12===0?0:255;}
 const animated=await sharp(animRaw,{raw:{width:3,height:8,channels:4,pageHeight:4}}).gif({delay:[100,250],loop:0}).toBuffer(),animatedFile=Test.outputPath('animated.gif');fs.writeFileSync(animatedFile,animated);
 await p.setInputFiles('#files',animatedFile);await p.waitForSelector('#import-dialog[open]');await p.click('#accept');await p.waitForFunction(()=>!SF.App.busy);const animation=await p.evaluate(()=>SF.Store.project.frames.map(f=>({index:f.sourceFrameIndex,durationUs:f.sourceDurationUs,originalSha:f.origin?.sha256})));assert.equal(animation.length,2);assert.deepEqual(animation.map(f=>f.index),[0,1]);assert.deepEqual(animation.map(f=>f.durationUs),[100000,250000]);assert.ok(animation.every(f=>f.originalSha===crypto.createHash('sha256').update(animated).digest('hex')));
 checks.push('Native ImageDecoder extracts both transparent GIF frames with source delay metadata and original provenance');
 // Invalid SVG exercises the same media API with actual browser File/Blob decoders.
 const rejected=await p.evaluate(async()=>{try{await SF.Media.importFiles([new File(['<svg><image href="https://example.com/a.png"/></svg>'],'remote.svg',{type:'image/svg+xml'})],{cancelled:false},()=>{});return '';}catch(e){return e.message;}});assert.match(rejected,/self-contained/);checks.push('External-resource SVG is rejected without a network request');
 assert.deepEqual(errors,[]);assert.deepEqual(requests,[]);fs.writeFileSync(Test.outputPath('browser-media-results.json'),JSON.stringify({browser:await b.version(),htmlSha256:crypto.createHash('sha256').update(fs.readFileSync(Test.projectPath('SpriteForge.html'))).digest('hex'),offline:true,checks,imported,animation,errors,requests},null,2));console.log('PASS '+checks.join('\nPASS '));
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
