const Test=require('./config.cjs');
// Pure correction math, native raster pixels, real originals and ZIP round trips. No browser control.
const assert=require('node:assert/strict'),fs=require('node:fs'),{sandbox,load}=require('./audio-test-runtime.cjs');
const {createCanvas,loadImage,Image}=Test.dependency('@napi-rs/canvas'),JSZip=require('../vendor/jszip.min.js');
function canvas(w=1,h=1){const c=createCanvas(w,h);c.toBlob=(cb,type='image/png')=>cb(new Blob([c.toBuffer(type)],{type}));return c;}
const s=sandbox({JSZip,Image,document:{createElement:tag=>tag==='canvas'?canvas():{click(){}}},createImageBitmap:async b=>loadImage(Buffer.from(await b.arrayBuffer()))});s.SF.Assets={sunny:'data:image/png;base64,'+fs.readFileSync(Test.projectPath('assets/sunny-smiles-reference.png')).toString('base64')};
const SF=load(s,['timeline','store','banks','media','clips','placement','corrections','directions','audio','simulator','playback','renderer','pack']),{Corrections:C,Placement:G,Store:S,Pack:P,Media:M,Clips:Cl,Directions:D,Timeline:T}=SF,sig={cancelled:false},progress=()=>{},near=(a,b,e=1e-7)=>assert.ok(Math.abs(a-b)<e,`${a} != ${b}`),json=x=>JSON.parse(JSON.stringify(x)),checks=[],ok=x=>checks.push(x);
async function drift(){const files=[];for(let i=0;i<5;i++){const c=canvas(128,128),x=40+i*8,y=110-i*2,q=1+i*.25,ctx=c.getContext('2d');ctx.translate(x,y);ctx.scale(q,q);ctx.fillStyle='#e7bc72';ctx.fillRect(-10,-30,20,30);files.push(new s.File([c.toBuffer('image/png')],`drift_${i+1}.png`,{type:'image/png'}));}return M.importFiles(files,sig,progress);}
function bounds(bytes){return loadImage(bytes).then(image=>{const c=canvas(image.width,image.height),ctx=c.getContext('2d');ctx.drawImage(image,0,0);const a=ctx.getImageData(0,0,c.width,c.height).data,b=[c.width,c.height,-1,-1];for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++)if(a[(y*c.width+x)*4+3]>128){b[0]=Math.min(b[0],x);b[1]=Math.min(b[1],y);b[2]=Math.max(b[2],x);b[3]=Math.max(b[3],y);}return b;});}
const key=(p,i)=>({...C.identity(G.resolve(p,'dance')),pivotX:40+i*8,pivotY:110-i*2,offsetX:64-(40+i*8),offsetY:(110-i*2)-112,scalePercent:100/(1+i*.25)});
(async()=>{const imported=await drift(),p=Cl.initialize({...imported,settings:{...S.defaults(),anchorX:64,anchorY:112,sourceFps:5,displayFps:5,rangeEnd:4,directionMode:'billboard'},extraClips:{}});S.replace(p);
C.upsert(p,'dance',0,'S',key(p,0));C.upsert(p,'dance',4,'S',key(p,4));near(C.evaluate(p,'dance',2).scalePercent,75);near(C.evaluate(p,'dance',2).offsetX,8);near(C.evaluate(p,'dance',-1).offsetX,24);near(C.evaluate(p,'dance',99).scalePercent,50);near(C.evaluate(p,'dance',4).scalePercent,50);
let track=C.track(p,'dance','S');track.keys[0].interpolation='hold';near(C.evaluate(p,'dance',3).scalePercent,100);near(C.evaluate(p,'dance',4).scalePercent,50);track.keys[0].interpolation='smooth';near(C.evaluate(p,'dance',1).scalePercent,100-50*.15625);for(let i=0;i<4;i+=.1)assert.ok(C.evaluate(p,'dance',i).scalePercent>=50&&C.evaluate(p,'dance',i).scalePercent<=100);track.keys[0].interpolation='linear';C.changed(p);ok('Linear/Hold/Smooth interpolation, exact endpoints, nearest-key hold and no smooth overshoot');
const initial=json(C.evaluate(p,'dance',2));for(const patch of [{sourceFps:60,displayFps:7,playbackSpeedPercent:170,rangeStart:1,rangeEnd:3,playbackMode:'ping_pong'},{sourceFps:5,displayFps:5,playbackSpeedPercent:100,rangeStart:0,rangeEnd:4,playbackMode:'ping_pong'}]){Object.assign(p.settings,patch);assert.deepEqual(json(C.evaluate(p,'dance',2)),initial);}const schedule=T.schedule(p.settings);assert.deepEqual(Array.from(schedule.entries.map(x=>x.frame)),[0,1,2,3,4,3,2,1]);for(const i of [1,2,3])assert.deepEqual(json(C.evaluate(p,'dance',i)),json(C.evaluate(p,'dance',schedule.entries.findLast(e=>e.frame===i).frame)));near(schedule.durationSeconds,1.6);ok('Source-frame keys ignore FPS/speed/range; ping-pong samples endpoints once and repeats identical corrections');
for(let i=0;i<5;i++)C.upsert(p,'dance',i,'S',key(p,i));const out=C.layout(p,'dance'),results=[];for(let i=0;i<5;i++){const blob=await D.prepared(p.frames[i],out.canvas,out.sourceAnchor,null,out,C.affine(C.evaluate(p,'dance',i)));results.push(await bounds(Buffer.from(await blob.arrayBuffer())));}for(const b of results)assert.deepEqual(b,results[0]);near(results[0][0]-out.anchor[0],-10);near(results[0][3]+1-out.anchor[1],0);ok('Actual drift PNGs normalize to equal alpha bounds and grounded feet using per-frame manual keys');
Object.assign(p.settings,{directionMode:'generated',widthPercent:150,heightPercent:80,shapeLinked:false,scalePercent:75,offsetXUnits:4,offsetYUnits:3});C.changed(p);const eight=C.layout(p,'dance'),g=G.resolve(p,'dance'),u=G.metrics(p,'dance').unitsPerPixel;for(const dir of D.order)for(let i=0;i<5;i++){const a=C.affine(C.evaluate(p,'dance',i)),m=C.matrix(p,'dance',i,dir,eight),r=D.resolve(p,'dance',dir).recipe;for(const [x,y]of [[0,0],[128,128],[40+i*8,110-i*2]]){const ox=m[0]*x+m[4],oy=m[3]*y+m[5];assert.ok(ox>=-1e-6&&ox<=eight.canvas[0]+1e-6&&oy>=-1e-6&&oy<=eight.canvas[1]+1e-6);near((ox-eight.anchor[0])*eight.unitsPerOutputPixel+4,((a.scale*x+a.x)-g.anchorX)*1.5*(r?.widthFactor??1)*(r?.mirror?-1:1)*u+4);near((eight.anchor[1]-oy)*eight.unitsPerOutputPixel+3,(g.anchorY-(a.scale*y+a.y))*.8*u+3);}}ok('Eight-view correction→shape/mirror→physical mapping agrees with stable root and applies authored scale once');
// Real imported views remain independent; front linking is explicit and generated views follow front.
p.directions.E={kind:'imported',frames:p.frames};C.changed(p);near(C.evaluate(p,'dance',1,'E').scalePercent,100);C.own(p,'dance','E').link='S';C.changed(p);near(C.evaluate(p,'dance',1,'E').scalePercent,80);C.own(p,'dance','E').enabled=false;near(C.evaluate(p,'dance',1,'E').scalePercent,100);delete p.corrections.dance.tracks.E;C.changed(p);ok('Imported views start independently; explicitly linked front tracks and disabled links work');
const before=json(p.corrections),saved=await P.save(p,sig,progress),again=await P.reopen(saved,sig,progress);assert.deepEqual(json(again.corrections),before);assert.deepEqual(json(again.placements),json(p.placements));for(let i=0;i<5;i++)assert.equal(await M.hash(again.frames[i].blob),await M.hash(p.frames[i].blob));again.preview.correctionView='original';const source=await P.source(again,sig,progress),zip=await JSZip.loadAsync(await source.arrayBuffer()),root='Modding_Ready_Sprite_Files/my_sprite/',manifest=JSON.parse(await zip.file(root+'manifest.json').async('string')),clip=manifest.clips.dance;assert.equal(manifest.schemaVersion,6);assert.deepEqual(clip.corrections,before.dance);assert.deepEqual(JSON.parse(await zip.file(root+clip.schedule).async('string')),json(T.schedule(again.settings)));for(const [dir,view]of Object.entries(clip.directions))for(const f of view.frames){const bytes=await zip.file(root+f.file).async('nodebuffer'),image=await loadImage(bytes);assert.equal(image.width,clip.placement.canvas[0]);assert.equal(image.height,clip.placement.canvas[1]);assert.deepEqual(f.sourceToOutputMatrix,json(C.matrix(again,'dance',f.index,dir,C.layout(again,'dance'))));assert.equal(f.sha256,await M.hash(new Blob([bytes])));}assert.equal(clip.directions.S.frames[0].correction.offsetX,24);ok('Schema 7 originals/keys round trip; Source Pack v6 bakes saved keys despite Original preview and retains exact schedule/matrices/hashes');
const legacy=await JSZip.loadAsync(await saved.arrayBuffer()),meta=JSON.parse(await legacy.file('project.json').async('string'));meta.schemaVersion=5;delete meta.corrections;delete meta.correctionVersion;legacy.file('project.json',JSON.stringify(meta));assert.deepEqual(json((await P.reopen(await legacy.generateAsync({type:'blob'}),sig,progress)).corrections),{});const damaged=await JSZip.loadAsync(await saved.arrayBuffer()),bad=JSON.parse(await damaged.file('project.json').async('string'));bad.corrections.dance.tracks.S.keys[0].sha256='0'.repeat(64);damaged.file('project.json',JSON.stringify(bad));await assert.rejects(P.reopen(await damaged.generateAsync({type:'blob'}),sig,progress),/source frame/);ok('Legacy schema 5 gains identity corrections; bad source bindings are rejected on reopen');
S.replace(again);S.commit({clipId:'main_clip'});assert.ok(again.corrections.main_clip);assert.equal(again.corrections.dance,undefined);S.history(false);assert.ok(again.corrections.dance);S.commitCorrections(()=>C.upsert(again,'dance',0,'S',{...key(again,0),offsetX:40}));S.history(false);near(C.evaluate(again,'dance',0).offsetX,24);S.history(true);near(C.evaluate(again,'dance',0).offsetX,40);assert.throws(()=>S.commitCorrections(()=>C.upsert(again,'dance',0,'S',{...key(again,0),scalePercent:0})),/scalePercent/);near(C.evaluate(again,'dance',0).offsetX,40);ok('General Undo/Redo, main clip renaming and invalid-key rollback preserve tracks');
const reordered={...again,frames:[...again.frames].reverse(),corrections:json(again.corrections)};C.remapAll(reordered);near(C.track(reordered,'dance').keys[0].scalePercent,50);C.validate(reordered);const duplicate={...p,frames:[p.frames[0],p.frames[0]],corrections:{dance:{outputMode:'expand',tracks:{S:{enabled:true,keys:[before.dance.tracks.S.keys[0]],review:[]}}}}};C.remapAll(duplicate);assert.equal(C.track(duplicate,'dance').review.length,1);assert.equal(C.track(duplicate,'dance').keys.length,0);const replaced={...again,frames:again.frames.map(f=>({...f,sha256:'b'.repeat(64)})),corrections:json(again.corrections)};C.remapAll(replaced);assert.equal(C.track(replaced,'dance').review.length,5);near(C.evaluate(replaced,'dance',2).scalePercent,100);await assert.rejects(P.source(replaced,sig,progress),/unmatched/);C.track(replaced,'dance').enabled=false;C.changed(replaced);await P.source(replaced,sig,progress);ok('Reordering follows unique source identity; duplicates/replaced footage require review; disabled review explicitly bypasses export');
// Deliberate cropping and hard bounds, checked against actual pixels.
const crop=Cl.initialize({...imported,settings:{...S.defaults(),rangeEnd:4,anchorX:64,anchorY:112,directionMode:'billboard'},corrections:{}});C.upsert(crop,'dance',0,'S',{...C.identity(G.resolve(crop,'dance')),offsetX:100});const expanded=C.layout(crop,'dance');assert.equal(expanded.canvas[0],228);assert.equal(expanded.wouldCrop,true);C.profile(crop,'dance').outputMode='clip';C.changed(crop);const clipped=C.layout(crop,'dance');assert.equal(clipped.canvas[0],128);const cropBlob=await D.prepared(crop.frames[0],clipped.canvas,clipped.sourceAnchor,null,clipped,C.affine(C.evaluate(crop,'dance',0)));assert.equal((await bounds(Buffer.from(await cropBlob.arrayBuffer())))[2],-1);assert.equal(C.render(crop,'dance',0,'S',[1,1],true).clip,null);C.profile(crop,'dance').outputMode='expand';C.upsert(crop,'dance',0,'S',{...C.identity(G.resolve(crop,'dance')),offsetX:8192});assert.throws(()=>C.layout(crop,'dance'),/8192/);assert.equal(C.layout(crop,'dance',false).canvas[0],8320);C.profile(crop,'dance').outputMode='clip';C.changed(crop);assert.equal(C.layout(crop,'dance').canvas[0],128);ok('Fixed sequence bounds, deliberate raster clipping, Original unclipped comparison and over-8192 preflight guard');
fs.writeFileSync(Test.outputPath('a3-corrections.spriteforge.zip'),Buffer.from(await saved.arrayBuffer()));fs.writeFileSync(Test.outputPath('a3_source_pack_v6.zip'),Buffer.from(await source.arrayBuffer()));fs.writeFileSync(Test.outputPath('a3-correction-checks.json'),JSON.stringify({version:'0.6.2',checks,freshBrowserAcceptance:false,method:'Pure math, native Canvas/PNG/ZIP, synthetic originals; no browser navigation or audible output.'},null,2)+'\n');console.log(checks.join('\n'));
})().catch(e=>{console.error(e);process.exit(1)});
