// Native raster decoders and Canvas, not a browser UI acceptance test.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{webcrypto}=require('node:crypto'),{File}=require('node:buffer');
const deps='/Users/seamuswulff/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/';
const {createCanvas,loadImage}=require(deps+'@napi-rs/canvas'),sharp=require(deps+'sharp'),JSZip=require('../vendor/jszip.min.js');
const checks=[],record=(s)=>checks.push(s),surfaces=[];
function canvas(){const c=createCanvas(1,1);c.toBlob=(cb,type='image/png')=>{try{cb(new Blob([c.toBuffer(type)],{type}));}catch{cb(null);}};surfaces.push(c);return c;}
const document={createElement(type){if(type==='canvas')return canvas();if(type==='a')return {click(){}};throw Error(type);}};
const sandbox={SF:{},Blob,File,crypto:webcrypto,TextDecoder,Uint8Array,ArrayBuffer,DataView,document,JSZip,URL,window:{},setTimeout:(fn,ms)=>ms===60000?0:setTimeout(fn,ms),createImageBitmap:async blob=>{const c=await loadImage(await sharp(Buffer.from(await blob.arrayBuffer())).png().toBuffer());c.close=()=>{};return c;}};
vm.createContext(sandbox);for(const m of ['timeline','store','banks','media','clips','placement','corrections','directions','simulator','playback','pack'])vm.runInContext(fs.readFileSync(`sprite-forge/src/${m}.js`,'utf8'),sandbox);const {Media:M,Pack:P,Store:S,Clips:C}=sandbox.SF;
const sig={cancelled:false},progress=()=>{},file=(bytes,name,type='')=>new File([bytes],name,{type});
(async()=>{
 const c=canvas();c.width=9;c.height=13;const ctx=c.getContext('2d');ctx.fillStyle='#e7bc72';ctx.fillRect(2,3,4,8);const input=c.toBuffer('image/png'),base=sharp(input);
 const list=[file(await base.clone().flatten({background:'#8f1b15'}).jpeg().toBuffer(),'pose_1.jpeg'),file(input,'pose_2.png'),file(await base.clone().webp({lossless:true}).toBuffer(),'pose_3.webp'),file(await base.clone().gif().toBuffer(),'pose_4.gif'),file(await base.clone().avif().toBuffer(),'pose_5.avif'),file(Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="5" height="7"><rect width="5" height="7" fill="gold"/></svg>'),'pose_6.svg')];
 const tiny=await sharp({create:{width:1,height:1,channels:4,background:'#e7bc72'}}).png().toBuffer();const tinyP=await M.importFiles([file(tiny,'tiny_1.png')],sig,progress);assert.deepEqual(Array.from(tinyP.canvas),[1,1]);assert.deepEqual(Array.from(tinyP.anchor),[.5,1]);record('Actual 1 × 1 image import and feet anchor');
 const imported=await M.importFiles(list.reverse(),sig,progress);assert.equal(imported.frames.length,6);assert.equal(imported.frames[0].name,'pose_1.jpeg');assert.equal(imported.frames[0].transparent,false);assert.equal(imported.frames[1].transparent,true);assert.deepEqual(Array.from(imported.frames[1].bounds),[2,3,5,10]);assert.deepEqual(Array.from(imported.canvas),[9,13]);assert.equal(imported.mixed,true);record('JPEG/PNG/WebP/GIF/AVIF/SVG ordering, alpha bounds, opaque warnings and uneven dimensions');
 const normalized=await M.normalized(imported.frames[0],[9,13]);assert.equal(normalized.type,'image/png');assert.equal(Buffer.from(await normalized.arrayBuffer()).subarray(1,4).toString(),'PNG');record('Opaque JPEG exports real PNG even with unchanged dimensions');
 await assert.rejects(M.importFiles([file(input,'bad_1.png'),file(input,'bad_1.webp')],sig,progress),/Duplicate frame index/);await assert.rejects(M.importFiles([file(Buffer.from('not an image'),'bad.psd','image/vnd.adobe.photoshop')],sig,progress),/cannot decode/);await assert.rejects(M.importFiles([file(Buffer.from('<svg><image href="https://example.com/a.png"/></svg>'),'remote.svg')],sig,progress),/self-contained/);record('Duplicate numbers, unsupported source and external-resource SVG rejected');
 for(const n of [1,8192])M.sizeCheck(n,n,'fixture');assert.throws(()=>M.sizeCheck(8193,1,'fixture'),/8192/);assert.throws(()=>M.sizeCheck(0,1,'fixture'),/8192/);
 const huge=await sharp({create:{width:8192,height:8192,channels:4,background:{r:15,g:20,b:5,alpha:1}}}).png().toBuffer();const big=await M.importFiles([file(huge,'big_1.png')],sig,progress);assert.equal(big.frames[0].width,8192);assert.equal(big.frames[0].height,8192);assert.deepEqual(Array.from(big.frames[0].bounds),[0,0,8191,8191]);assert.ok(surfaces.filter(x=>x.width===8192).every(x=>x.height<=128));record('Actual 8192 × 8192 opaque import with strip scanning; 8193 and zero rejected');big.frames.length=0;
 const p=C.initialize({...imported,settings:{...S.defaults(),rangeEnd:5,anchorX:imported.anchor[0],anchorY:imported.anchor[1],directionMode:'billboard'}});S.replace(p);const saved=await P.save(p,sig,progress),again=await P.reopen(saved,sig,progress);for(let i=0;i<6;i++){assert.equal(await M.hash(again.frames[i].blob),await M.hash(p.frames[i].blob));assert.equal(again.frames[i].blob.type,p.frames[i].blob.type);}assert.equal(again.settings.anchorY,p.settings.anchorY);record('Schema 7 save/reopen preserves mixed-format original bytes, MIME types and grounding');
 const pack=await P.source(again,sig,progress),z=await JSZip.loadAsync(await pack.arrayBuffer()),root='Modding_Ready_Sprite_Files/my_sprite/';const manifest=JSON.parse(await z.file(root+'manifest.json').async('string'));for(const f of manifest.clips.dance.directions.S.frames){const bytes=await z.file(root+f.file).async('nodebuffer');assert.equal(bytes.subarray(1,4).toString(),'PNG');const meta=await sharp(bytes).metadata();assert.equal(meta.width,9);assert.equal(meta.height,13);}record('Source Pack contains organized actual PNGs and common-canvas padding');
 // Real animated GIF encoded by sharp from two stacked pages.
 // Force two different frames; identical frames may be coalesced by GIF encoder.
 const raw=Buffer.alloc(3*4*4*2);for(let i=0;i<raw.length;i+=4){raw[i]=i<48?255:0;raw[i+1]=i<48?0:255;raw[i+3]=i%12===0?0:255;}
 const anim=await sharp(raw,{raw:{width:3,height:8,channels:4,pageHeight:4}}).gif({delay:[100,250],loop:0}).toBuffer();assert.equal(M.format(new Uint8Array(anim),file(anim,'anim.gif')).animated,true);
 await assert.rejects(M.importFiles([file(anim,'anim_1.gif')],sig,progress),/animated extraction is unavailable/);record('Animated GIF is detected and requires extraction support; no silent first-frame import');
 const pages=[await sharp(anim,{page:0}).png().toBuffer(),await sharp(anim,{page:1}).png().toBuffer()];let closed=0;
 sandbox.ImageDecoder=class {static async isTypeSupported(type){return type==='image/gif';}tracks={ready:Promise.resolve(),selectedTrack:{frameCount:2}};completed=Promise.resolve();async decode({frameIndex}){const image=await loadImage(pages[frameIndex]);image.displayWidth=3;image.displayHeight=4;image.duration=[100000,250000][frameIndex];image.close=()=>closed++;return {image};}close(){closed++;}};
 const extracted=await M.importFiles([file(anim,'anim_1.gif')],sig,progress);assert.equal(extracted.frames.length,2);assert.equal(extracted.frames[0].transparent,true);assert.equal(extracted.frames[1].sourceDurationUs,250000);assert.equal(closed,3);assert.equal(await M.hash(extracted.frames[0].origin.blob),await M.hash(anim.buffer.slice(anim.byteOffset,anim.byteOffset+anim.byteLength)));
 const ap=C.initialize({...extracted,settings:{...S.defaults(),rangeEnd:1,anchorX:1,anchorY:4,directionMode:'billboard'}}),az=await P.save(ap,sig,progress);delete sandbox.ImageDecoder;const ar=await P.reopen(az,sig,progress);assert.equal(ar.frames[1].sourceDurationUs,250000);assert.equal(await M.hash(ar.frames[0].origin.blob),await M.hash(ap.frames[0].origin.blob));assert.equal(ar.frames[0].origin,ar.frames[1].origin);record('Animated extraction orchestration, alpha, resource cleanup, source delays and original GIF save/reopen (mock ImageDecoder; real GIF/PNG bytes)');
 for(const old of ['legacy-v1','fixture','salvatore_front']){const blob=new Blob([fs.readFileSync(`sprite-forge/evidence/${old}.spriteforge.zip`)]);const oldP=await P.reopen(blob,sig,progress);assert.equal(oldP.settings.directionMode,'billboard');if(old==='salvatore_front'){assert.equal(oldP.frames.length,70);assert.deepEqual(Array.from(oldP.canvas),[1080,1080]);assert.ok(oldP.frames.every(f=>f.transparent&&f.bounds[3]<1080));}}record('Legacy schema 1/2 projects and actual 70-frame Salvatore front reopen with alpha intact');
 fs.writeFileSync('sprite-forge/evidence/media-0.6.0-checks.json',JSON.stringify({version:'0.6.0',checks,browserAcceptance:false,note:'Native raster/Canvas checks plus mock ImageDecoder/Web Audio are not fresh browser interaction tests.'},null,2));console.log(checks.join('\n'));
})().catch(e=>{console.error(e);process.exit(1);});
