const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const deps=process.env.SPRITE_FORGE_NODE_MODULES||'/Users/seamuswulff/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';const {chromium}=require(path.join(deps,'playwright')),JSZip=require(path.join(deps,'jszip'));
const root=path.resolve('sprite-forge'),ev=path.join(root,'evidence'),url='file://'+path.join(root,'SpriteForge.html'),checks=[];const pass=(name,detail='')=>{checks.push({name,detail,passed:true});console.log('PASS',name,detail);};
function wav(){const rate=48000,n=rate*2,b=Buffer.alloc(44+n*4);b.write('RIFF');b.writeUInt32LE(b.length-8,4);b.write('WAVE',8);b.write('fmt ',12);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(2,22);b.writeUInt32LE(rate,24);b.writeUInt32LE(rate*4,28);b.writeUInt16LE(4,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(n*4,40);for(let i=0;i<n;i++){const tone=Math.sin(i/rate*2*Math.PI*440);b.writeInt16LE(Math.round(tone*.2*32767),44+i*4);b.writeInt16LE(Math.round(tone*.4*32767),46+i*4);}return b;}
const wavPath=path.join(root,'fixtures','stereo-tone-48k.wav');fs.writeFileSync(wavPath,wav());
(async()=>{const browser=await chromium.launch({executablePath:process.env.SPRITE_FORGE_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
const context=await browser.newContext({offline:true,acceptDownloads:true,viewport:{width:1560,height:1100}}),page=await context.newPage(),errors=[],remote=[];page.on('pageerror',e=>errors.push(e.message));context.on('request',r=>{if(/^https?:/.test(r.url()))remote.push(r.url());});await page.goto(url);
const ready=()=>page.waitForFunction(()=>!SF.App.busy,{timeout:120000}),tab=id=>page.click(`[data-tab="${id}"]`),set=async(id,value)=>{await page.locator('#'+id).fill(String(value));await page.locator('#'+id).press('Tab');},fixture=[10,3,2,1].map(n=>path.join(root,`fixtures/numbered/frame_${n}.png`));
await page.setInputFiles('#files',fixture);await page.waitForSelector('#import-dialog[open]');await page.click('#accept');await tab('animation');await set('sourceFps',4);await set('displayFps',8);await page.selectOption('#playbackMode','ping_pong');await tab('directions');await page.selectOption('#directionMode','generated');
await page.locator('#scrub').evaluate(el=>{el.value='.76';el.dispatchEvent(new Event('input',{bubbles:true}));});const pose=await page.locator('#frame-label').textContent();for(const dir of ['S','SE','E','NE','N','NW','W','SW']){await page.click(`#direction-picker [data-direction="${dir}"]`);assert.equal(await page.locator('#frame-label').textContent(),pose);}assert.equal(await page.locator('#duration').textContent(),'1.500000 s');pass('Eight-direction phase continuity','All eight views retain the same ping-pong pose and cycle.');
const generated=await page.evaluate(async()=>{const p=SF.Store.project,f=p.frames[0],get=async d=>{const blob=await SF.Directions.prepared(f,p.canvas,[p.settings.anchorX,p.settings.anchorY],d==='S'?null:SF.Directions.recipe(p.settings,d)),bitmap=await createImageBitmap(blob),c=document.createElement('canvas');c.width=c.height=256;c.getContext('2d').drawImage(bitmap,0,0);bitmap.close();const a=c.getContext('2d').getImageData(0,0,256,256).data;let red=0,redN=0,blue=0,blueN=0;for(let i=0;i<a.length;i+=4)if(a[i+3]>128){if(a[i]>a[i+2]*1.8){red+=(i/4)%256;redN++;}if(a[i+2]>a[i]*1.8){blue+=(i/4)%256;blueN++;}}return {red:red/redN,blue:blue/blueN,alpha:Array.from(a).filter((_,i)=>i%4===3)};};const front=await get('S'),left=await get('W'),rear=await get('N');return {front:[front.red,front.blue],left:[left.red,left.blue],rearAlphaMatches:front.alpha.every((x,i)=>x===rear.alpha[i]),recipe:SF.Directions.recipe(p.settings,'W')};});assert.ok(generated.front[0]<generated.front[1]);assert.ok(generated.left[0]>generated.left[1]);assert.equal(generated.recipe.widthFactor,.45);assert.equal(generated.rearAlphaMatches,true);pass('Generated view orientation and alpha','Left mirrors the asymmetric markers; rear darkening preserves alpha exactly.');
await page.locator('#orbit').evaluate(el=>{el.value='20';el.dispatchEvent(new Event('input'));});assert.equal(await page.evaluate(()=>SF.Store.project.settings.previewDirection),'S');await page.locator('#orbit').evaluate(el=>{el.value='30';el.dispatchEvent(new Event('input'));});assert.equal(await page.evaluate(()=>SF.Store.project.settings.previewDirection),'SE');pass('Orbit boundary hysteresis','20° retains S; 30° crosses to SE.');
await page.setInputFiles('#direction-files',fixture.slice(1));await ready();assert.match(await page.locator('#status').textContent(),/expects 4/);await page.selectOption('#direction-import','E');await page.setInputFiles('#direction-files',fixture);await page.waitForSelector('#import-dialog[open]');await page.click('#accept');await ready();assert.equal(await page.evaluate(()=>SF.Store.project.directions.E.frames.length),4);await tab('directions');await page.click('#direction-picker [data-direction="E"]');assert.equal(await page.locator('#view-kind').textContent(),'IMPORTED');pass('Real view import and mismatch rejection','Matching four-frame E overrides the generated view; three-frame view rejected.');
let download=page.waitForEvent('download');await page.click('#contact-download');await (await download).saveAs(path.join(ev,'directions-sheet.png'));await page.screenshot({path:path.join(ev,'studio-directions.png'),fullPage:true});
await tab('states');await page.locator('[data-panel="states"] details').first().locator('summary').click();await page.setInputFiles('#clip-files',fixture);await page.waitForSelector('#import-dialog[open]');await page.click('#accept');await ready();assert.equal(await page.evaluate(()=>SF.Studio.clipId),'idle');await tab('animation');await set('sourceFps',2);assert.equal(await page.evaluate(()=>SF.Store.project.extraClips.idle.timing.sourceFps),2);assert.equal(await page.evaluate(()=>SF.Store.project.settings.sourceFps),4);await tab('states');await page.selectOption('#gallery-state','neutral_idle');await page.selectOption('#state-clip','idle');assert.equal(await page.evaluate(()=>SF.Studio.clipId),'idle');pass('Extra clip timing and state assignment','Neutral idle uses its own 2 FPS clip; base remains 4 FPS.');
for(const state of await page.evaluate(()=>SF.Simulator.states)){await page.selectOption('#gallery-state',state);assert.equal(await page.evaluate(()=>SF.Studio.visual().state),state);}pass('State Gallery','All ten states are independently selectable, including inventory and repack.');
await tab('audio');for(const slot of ['music_loop','defeat_sting','defeated_loop','release']){await page.selectOption('#audio-slot',slot);await page.setInputFiles('#audio-file',wavPath);await ready();assert.match(await page.locator('#audio-info').textContent(),/2ch/);}
await page.selectOption('#audio-slot','music_loop');await set('audio-trimStart',.25);await set('audio-trimEnd',1.25);await set('audio-loopStart',.5);await set('audio-loopEnd',1);await set('audio-gainDb',-6);await page.locator('#preview-volume').evaluate(el=>{el.value='33';el.dispatchEvent(new Event('input'));});await page.click('#audio-converted');await ready();assert.match(await page.locator('#status').textContent(),/44100 samples/);assert.ok((await page.evaluate(()=>SF.Audio.activeSlots)).includes('converted'));await page.click('#audio-stop');await page.check('#audio-muted');assert.equal(await page.evaluate(()=>SF.Store.project.audio.music_loop.edits.muted),true);await page.uncheck('#audio-muted');pass('Audio editing and converted audition','Trim, loop points, baked gain, preview mute/volume and actual PCM WAV audition.');
await set('audio-trimEnd',99);assert.match(await page.locator('#status').textContent(),/Trim must stay inside/);assert.equal(await page.evaluate(()=>SF.Store.project.audio.music_loop.edits.trimEnd),1.25);await set('audio-gainDb',12);await page.click('#audio-converted');await ready();assert.match(await page.locator('#status').textContent(),/Audio clips/);await set('audio-gainDb',-6);pass('Audio range and clipping rejection','Invalid trim restores old edits; clipping blocks conversion.');
const mp3=path.resolve('work/source/Salvatore gon_ getcha (main asset source folder for GECK modding)/assets/sounds/res_sound_effect.mp3');await page.selectOption('#audio-slot','release');await page.setInputFiles('#audio-file',mp3);await ready();assert.ok(await page.evaluate(()=>SF.Store.project.audio.release.buffer.length>0));pass('Compressed audio decode','Existing Salvatore release MP3 decoded offline.');
await page.screenshot({path:path.join(ev,'studio-audio.png'),fullPage:true});
// Actual animation controls plus controllable browser time, fixed-step encounter.
await tab('animation');await page.selectOption('#active-clip','dance');await page.selectOption('#playbackMode','ping_pong');await tab('states');await page.clock.install();await page.clock.pauseAt(new Date());await page.click('#encounter-mode');await page.clock.runFor(6000);assert.ok(await page.evaluate(()=>SF.Studio.simulation.model.player.hp<100));
await page.locator('#preview').focus();const px=await page.evaluate(()=>SF.Studio.simulation.model.player.x);await page.keyboard.down('d');await page.clock.runFor(500);await page.keyboard.up('d');assert.ok((await page.evaluate(()=>SF.Studio.simulation.model.player.x))>px);pass('Encounter pursuit, player damage and controls','Hostile reaches player; WASD moves the marker under actual clock advancement.');
await page.click('#defeat-now');assert.ok((await page.evaluate(()=>SF.Audio.activeSlots)).includes('defeat_sting'));await page.clock.runFor(300);await page.click('#pickup');assert.equal(await page.evaluate(()=>SF.Studio.simulation.model.inventory),true);await page.clock.runFor(3000);assert.equal(await page.evaluate(()=>SF.Studio.simulation.model.state),'stored');assert.deepEqual(await page.evaluate(()=>SF.Audio.activeSlots),[]);pass('Early pickup cancels owned audio','Picking up during the sting cannot restart an orphan defeated loop.');
await page.click('#deploy');assert.equal(await page.evaluate(()=>SF.Studio.simulation.model.state),'deploying');await page.clock.runFor(40000);assert.equal(await page.evaluate(()=>SF.Studio.simulation.model.enemy.hp),0);assert.ok(await page.evaluate(()=>SF.Studio.simulation.model.events.some(e=>e.message==='Neutral roam')));assert.ok(['neutral_idle','neutral_roam'].includes(await page.evaluate(()=>SF.Studio.simulation.model.state)));pass('Deploy → combat → idle → roam','Release sound finishes; companion defeats the red block and wanders.');
await page.click('#pause-all');const frozen=await page.evaluate(()=>SF.Studio.simulation.model.timeSeconds);await page.clock.runFor(1000);assert.equal(await page.evaluate(()=>SF.Studio.simulation.model.timeSeconds),frozen);assert.equal(await page.evaluate(()=>SF.Audio.contextState),'suspended');await page.click('#play');await page.click('#repack');await page.clock.runFor(500);assert.equal(await page.evaluate(()=>SF.Studio.simulation.model.state),'stored');const bounds=await page.locator('#preview').boundingBox();await page.mouse.click(bounds.x+bounds.width*.65,bounds.y+bounds.height*.6);assert.equal(await page.evaluate(()=>SF.Studio.simulation.model.state),'deploying');assert.equal(await page.evaluate(()=>SF.App.playing),true);await page.clock.runFor(5000);await page.click('#spawn-enemy');await page.clock.runFor(100);assert.equal(await page.evaluate(()=>SF.Studio.simulation.model.state),'companion_combat');pass('Pause, repack, click deployment and reacquisition','Pause freezes time/audio; repeated deployment keeps one world actor.');
await page.click('#defeat-now');await page.clock.runFor(2300);assert.equal(await page.evaluate(()=>SF.Studio.simulation.model.state),'defeated');assert.ok((await page.evaluate(()=>SF.Audio.activeSlots)).includes('defeated_loop'));await page.click('#pickup');assert.deepEqual(await page.evaluate(()=>SF.Audio.activeSlots),[]);await page.click('#deploy');await page.clock.runFor(30000);await page.click('#pause-all');await page.screenshot({path:path.join(ev,'studio-encounter.png'),fullPage:true});assert.ok(await page.evaluate(()=>SF.Audio.activeVoices.every(v=>v.playbackRate===1)));pass('Completed defeat sting → ground loop','Full defeat starts the loop; pickup stops it; cycle repeats.');const unit=await page.evaluate(()=>SF.Renderer.sceneGeometry.unit);await page.locator('#zoom').evaluate(el=>{el.dispatchEvent(new PointerEvent('pointerdown'));el.value='200';el.dispatchEvent(new Event('input'));el.dispatchEvent(new Event('change'));});assert.ok(Math.abs((await page.evaluate(()=>SF.Renderer.sceneGeometry.unit))-unit*2)<1e-8);await page.clock.resume();
await tab('import');await set('characterId','milestone2');const expected=await page.evaluate(()=>({settings:SF.Store.clone(SF.Store.project.settings),simulation:SF.Store.project.simulation,stateClips:SF.Store.project.stateClips,preview:SF.Store.project.preview,audio:Object.fromEntries(Object.entries(SF.Store.project.audio).map(([k,a])=>[k,{sha256:a.sha256,edits:a.edits}]))}));
download=page.waitForEvent('download');await page.click('#save');const projectFile=path.join(ev,'milestone2.spriteforge.zip');await (await download).saveAs(projectFile);await ready();const saved=await JSZip.loadAsync(fs.readFileSync(projectFile),{checkCRC32:true}),metadata=JSON.parse(await saved.file('project.json').async('string'));assert.equal(metadata.schemaVersion,2);
const opened=await context.newPage();opened.on('pageerror',e=>errors.push(e.message));await opened.goto(url);await opened.setInputFiles('#project-file',projectFile);await opened.waitForFunction(()=>document.querySelector('#dirty').textContent==='Saved project',{timeout:120000});const actual=await opened.evaluate(()=>({settings:SF.Store.clone(SF.Store.project.settings),simulation:SF.Store.project.simulation,stateClips:SF.Store.project.stateClips,preview:SF.Store.project.preview,audio:Object.fromEntries(Object.entries(SF.Store.project.audio).map(([k,a])=>[k,{sha256:a.sha256,edits:a.edits}]))}));assert.deepEqual(actual,expected);assert.deepEqual(await opened.evaluate(()=>[SF.Store.project.directions.E.frames.length,SF.Store.project.extraClips.idle.frames.length]),[4,4]);pass('Full Milestone 2 project round trip','Directions, extra clips/timing, original audio hashes/edits, state mappings, orbit/volume and seed survive fresh-page reopen.');
download=opened.waitForEvent('download');await opened.click('#export');const packFile=path.join(ev,'milestone2_source_pack_v2.zip');await (await download).saveAs(packFile);await opened.waitForFunction(()=>!SF.App.busy,{timeout:120000});const zip=await JSZip.loadAsync(fs.readFileSync(packFile),{checkCRC32:true}),prefix='Modding_Ready_Sprite_Files/milestone2/',manifest=JSON.parse(await zip.file(prefix+'manifest.json').async('string'));assert.equal(manifest.capabilities.eightDirections,true);assert.equal(manifest.capabilities.fnvAssets,false);assert.equal(manifest.clips.dance.directions.E.kind,'imported');assert.equal(manifest.clips.dance.directions.W.kind,'generated');assert.equal(manifest.stateClips.neutral_idle,'idle');assert.equal(manifest.audio.music_loop.gainDbBaked,-6);assert.equal(manifest.audio.music_loop.loopStartSample,11025);assert.equal(manifest.audio.music_loop.loopEndSampleExclusive,33075);
const wave=await zip.file(prefix+manifest.audio.music_loop.file).async('nodebuffer');assert.equal(wave.toString('ascii',0,4),'RIFF');assert.equal(wave.toString('ascii',8,12),'WAVE');assert.equal(wave.readUInt16LE(20),1);assert.equal(wave.readUInt16LE(22),1);assert.equal(wave.readUInt32LE(24),44100);assert.equal(wave.readUInt16LE(34),16);assert.equal(wave.readUInt32LE(40),88200);let peak=0;for(let i=44;i<wave.length;i+=2)peak=Math.max(peak,Math.abs(wave.readInt16LE(i))/32768);assert.ok(Math.abs(peak-.3*10**(-6/20))<.002);for(const a of Object.values(manifest.audio)){const bytes=await zip.file(prefix+a.file).async('nodebuffer');assert.equal(bytes.toString('ascii',8,12),'WAVE');assert.equal(bytes.readUInt16LE(34),16);assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),a.sha256);}assert.ok(!JSON.stringify(manifest).includes('volumePercent'));assert.ok(!JSON.stringify(manifest).includes('orbitDegrees'));
const schedule=JSON.parse(await zip.file(prefix+manifest.clips.dance.schedule).async('string'));assert.deepEqual(schedule,await opened.evaluate(()=>SF.Timeline.schedule(SF.Store.project.settings)));pass('Complete Source Pack and binary WAV validation','Two clips × eight views, imported provenance, identical timeline schedule; real MP3 converted to PCM16, stereo downmixed/resampled to 44.1kHz and −6dB applied once.');
// Legacy schema migration remains readable without audio or direction fields.
const legacy=await JSZip.loadAsync(fs.readFileSync(projectFile));const legacyProject=JSON.parse(await legacy.file('project.json').async('string'));legacyProject.schemaVersion=1;for(const key of ['directions','extraClips','simulation','preview'])delete legacyProject[key];legacyProject.audio={};legacyProject.stateClips={};for(const key of ['directionMode','previewDirection','generatedSideWidthPercent','rearDarknessPercent','mirrorDirections'])delete legacyProject.settings[key];legacy.file('project.json',JSON.stringify(legacyProject));const legacyFile=path.join(ev,'legacy-v1.spriteforge.zip');fs.writeFileSync(legacyFile,await legacy.generateAsync({type:'nodebuffer'}));await opened.setInputFiles('#project-file',legacyFile);await opened.waitForFunction(()=>!SF.App.busy&&Object.keys(SF.Store.project.audio).length===0,{timeout:120000});assert.equal(await opened.evaluate(()=>SF.Store.project.settings.directionMode),'billboard');assert.equal(await opened.evaluate(()=>SF.Store.project.frames.length),4);pass('Legacy project migration','Schema 1 projects reopen with explicit Milestone 2 defaults.');
assert.equal(errors.length,0,errors.join('\n'));assert.equal(remote.length,0);pass('Offline Milestone 2 browser operation','No network requests or browser exceptions.');fs.writeFileSync(path.join(ev,'milestone2-results.json'),JSON.stringify({browser:await browser.version(),platform:process.platform,offline:true,checks,errors,remoteRequests:remote.length},null,2));
}finally{await browser.close();}})().catch(e=>{console.error(e);fs.writeFileSync(path.join(ev,'milestone2-failure.json'),JSON.stringify({checks,error:String(e.stack)},null,2));process.exit(1)});
