// Native Canvas/ZIP and renderer geometry checks. No browser is navigated or controlled.
const assert=require('node:assert/strict'),fs=require('node:fs'),{sandbox,load}=require('./audio-test-runtime.cjs');
const deps='/Users/seamuswulff/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/',{createCanvas,loadImage,Image}=require(deps+'@napi-rs/canvas'),JSZip=require('../vendor/jszip.min.js');
function canvas(){const c=createCanvas(1,1);c.toBlob=(cb,type='image/png')=>cb(new Blob([c.toBuffer(type)],{type}));return c;}
const s=sandbox({JSZip,Image,document:{createElement:tag=>tag==='canvas'?canvas():{click(){}}},createImageBitmap:async b=>loadImage(Buffer.from(await b.arrayBuffer()))});s.window.devicePixelRatio=1;s.SF.Assets={sunny:'data:image/png;base64,'+fs.readFileSync('sprite-forge/assets/sunny-smiles-reference.png').toString('base64')};
const {Placement:G,Clips:C,Store:S,Media:M,Pack:P,Directions:D,Renderer:R}=load(s,['timeline','store','banks','media','clips','placement','corrections','directions','audio','simulator','playback','renderer','pack']),sig={cancelled:false},progress=()=>{},checks=[],ok=t=>checks.push(t),near=(a,b,tolerance=1e-8)=>assert.ok(Math.abs(a-b)<tolerance,`${a} differs from ${b}`);
async function sequence(w,h,name){const c=canvas();c.width=w;c.height=h;const ctx=c.getContext('2d');ctx.fillStyle='#e7bc72';ctx.fillRect(w*.2,h*.1,w*.6,h*.8);ctx.fillStyle='#ff2020';ctx.fillRect(w/2-3,h*.9-6,6,6);return M.importFiles([new s.File([c.toBuffer('image/png')],name+'_1.png',{type:'image/png'})],sig,progress);}
(async()=>{const main=await sequence(256,256,'main'),attack=await sequence(400,600,'attack'),idle=await sequence(128,320,'idle');const p=C.initialize({...main,settings:{...S.defaults(),anchorX:128,anchorY:230.4,rangeEnd:0,showReference:false},extraClips:{attack:{...attack,timing:{sourceFps:12,playbackSpeedPercent:100,displayFps:8,playbackMode:'once',rangeStart:0,rangeEnd:0},directions:{}},idle:{...idle,timing:{sourceFps:6,playbackSpeedPercent:100,displayFps:6,playbackMode:'forward_loop',rangeStart:0,rangeEnd:0},directions:{}}},stateClips:{hostile_attack:'attack',neutral_idle:'idle',neutral_roam:'idle'}});
G.validate(p);near(G.resolve(p,'attack').anchorX,200);near(G.resolve(p,'attack').anchorY,540);near(G.metrics(p,'attack').heightUnits,128);assert.equal(G.resolve(p,'attack').inherited,true);ok('Different native canvases inherit normalized roots and main physical calibration');
G.set(p,'attack',{anchorX:200,anchorY:540,referenceCanvasHeightUnits:200,scalePercent:80,widthPercent:250,heightPercent:60,shapeLinked:false});G.set(p,'idle',{anchorX:64,anchorY:288,referenceCanvasHeightUnits:128,scalePercent:100});near(G.metrics(p,'attack').heightUnits,96);near(G.metrics(p,'attack').widthUnits,400/600*200*.8*2.5);assert.equal(p.settings.scalePercent,100);ok('Per-clip root/calibration/scale and unlinked shape leave main unchanged');
S.replace(p);S.commitPlacement('attack',{widthPercent:300});assert.equal(G.resolve(p,'attack').heightPercent,60);S.history(false);assert.equal(G.resolve(p,'attack').widthPercent,250);S.history(true);assert.equal(G.resolve(p,'attack').widthPercent,300);S.history(false);S.commitPlacement('attack',{shapeLinked:true});assert.equal(G.resolve(p,'attack').heightPercent,250);S.history(false);const snapshot=JSON.stringify(p.placements);assert.throws(()=>S.commitPlacement('attack',{anchorY:601}),/anchorY/);assert.equal(JSON.stringify(p.placements),snapshot);ok('Placement Undo/Redo, linked axes and invalid-edit rollback');
const stage=canvas();stage.getBoundingClientRect=()=>({width:880,height:520,left:0,top:0});stage.setPointerCapture=()=>{};R.init(stage);let clipId='dance',state='hostile',view='S';s.SF.Studio={visual:()=>({clipId,state,direction:view,mode:'workbench',stateAge:0})};
for(const id of ['dance','attack','idle','attack','dance']){clipId=id;R.draw(p,0);const t=R.transform;near(t.x+t.anchor[0]*t.fx,t.pivot);near(t.y+t.anchor[1]*t.fy,t.floor);assert.equal(t.clipId,id);}
clipId='attack';R.draw(p,0);const t=R.transform,root={clientX:t.x+t.anchor[0]*t.fx,clientY:t.y+t.anchor[1]*t.fy,pointerId:1};assert.equal(R.begin(root,p.settings),true);const moved=R.move({clientX:t.x+120*t.fx,clientY:t.y+450*t.fy},p);near(moved.anchorX,120);near(moved.anchorY,450);R.end();G.set(p,'attack',{offsetXUnits:10,offsetYUnits:5});R.draw(p,0);const u=520*.63/p.settings.referenceCanvasHeightUnits;near(R.transform.x+200*R.transform.fx,R.transform.pivot+10*u);near(R.transform.y+540*R.transform.fy,R.transform.floor-5*u);G.set(p,'attack',{offsetXUnits:0,offsetYUnits:0});ok('Actual renderer roots remain on shared floor across clips; drag inversion uses independent X/Y scales and offsets');
const originalDraw=D.draw;let encounterDraw;D.draw=(...args)=>{encounterDraw={args,matrix:args[0].getTransform()};return originalDraw(...args);};const model=s.SF.Simulator.create(p.simulation).model;s.SF.Studio.visual=()=>({clipId:'attack',direction:'S',mode:'encounter',state:'hostile',stateAge:0,model});R.draw(p,0);near(encounterDraw.args[2][0],200);near(encounterDraw.args[2][1],540);near(encounterDraw.args[5][0],G.metrics(p,'attack',R.sceneGeometry.unit).factors[0]);near(encounterDraw.args[5][1],G.metrics(p,'attack',R.sceneGeometry.unit).factors[1]);near(encounterDraw.matrix.e,R.sceneGeometry.ox+model.actor.x*R.sceneGeometry.unit,1e-4);near(encounterDraw.matrix.f,R.sceneGeometry.oy+model.actor.z*R.sceneGeometry.unit*.6,1e-4);D.draw=originalDraw;s.SF.Studio.visual=()=>({clipId,state,direction:view,mode:'workbench',stateAge:0});ok('Encounter renderer uses assigned clip root, independent factors and shared actor ground position');
for(const id of C.ids(p)){const recipes=D.order.map(dir=>D.resolve(p,id,dir).recipe),out=G.output(p,id,recipes),g=G.resolve(p,id),m=G.metrics(p,id);for(const recipe of recipes)for(const [x,y] of [[0,0],[g.canvas[0],0],[0,g.canvas[1]],[g.anchorX,g.anchorY],[g.canvas[0],g.canvas[1]]]){const dx=(x-g.anchorX)*out.shape[0]*(recipe?.widthFactor??1)*(recipe?.mirror?-1:1),dy=(y-g.anchorY)*out.shape[1],ox=out.anchor[0]+dx,oy=out.anchor[1]+dy;assert.ok(ox>=-1e-8&&ox<=out.canvas[0]+1e-8&&oy>=-1e-8&&oy<=out.canvas[1]+1e-8);near((ox-out.anchor[0])*out.unitsPerOutputPixel+out.offsetUnits[0],dx*m.unitsPerPixel+g.offsetXUnits);near((out.anchor[1]-oy)*out.unitsPerOutputPixel+out.offsetUnits[1],-dy*m.unitsPerPixel+g.offsetYUnits);}}
ok('All eight views: transformed bounds retain full canvas and source→PNG→physical coordinates match preview');
const fractional=C.initialize({...await sequence(9,13,'tiny'),settings:{...S.defaults(),anchorX:4.5,anchorY:13,rangeEnd:0,directionMode:'billboard'}});assert.deepEqual(Array.from(G.output(fractional,'dance').canvas),[9,13]);near(G.output(fractional,'dance').anchor[0],4.5);const over=C.initialize({...p,settings:{...p.settings},placements:{...p.placements},extraClips:{...p.extraClips,large:{canvas:[8192,8192],frames:p.frames,timing:p.extraClips.idle.timing,directions:{}}}});G.set(over,'large',{widthPercent:101,heightPercent:100,shapeLinked:false});assert.throws(()=>G.output(over,'large'),/8192/);const invalid={...p,placements:{ghost:{inherit:true}}};assert.throws(()=>G.validate(invalid),/profile/);ok('Fractional-root identity output preserves dimensions; oversized output and orphan profiles fail explicitly');
const saved=await P.save(p,sig,progress),again=await P.reopen(saved,sig,progress);for(const id of C.ids(p)){assert.deepEqual(Array.from(C.canvas(again,id)),Array.from(C.canvas(p,id)));assert.deepEqual(JSON.parse(JSON.stringify(G.resolve(again,id))),JSON.parse(JSON.stringify(G.resolve(p,id))));for(let i=0;i<C.get(p,id).frames.length;i++)assert.equal(await M.hash(C.get(p,id).frames[i].blob),await M.hash(C.get(again,id).frames[i].blob));}assert.equal(again.stateClips.hostile_attack,'attack');ok('Schema 7 save/reopen preserves different native canvases, original bytes, placement profiles and state assignments');
const source=await P.source(again,sig,progress),zip=await JSZip.loadAsync(await source.arrayBuffer()),rootPath='Modding_Ready_Sprite_Files/my_sprite/',manifest=JSON.parse(await zip.file(rootPath+'manifest.json').async('string'));assert.equal(manifest.schemaVersion,6);for(const [id,c]of Object.entries(manifest.clips)){assert.equal(c.placement.scaleBakedIntoPixels,false);assert.equal(c.placement.shapeBakedIntoPixels,true);c.placement.canvas.forEach((n,i)=>near(c.placement.physicalOutputCanvasUnits[i],n*c.placement.unitsPerOutputPixel));for(const direction of Object.values(c.directions))for(const f of direction.frames){const bytes=await zip.file(rootPath+f.file).async('nodebuffer'),image=await loadImage(bytes);assert.equal(image.width,c.placement.canvas[0]);assert.equal(image.height,c.placement.canvas[1]);assert.equal(await M.hash(new Blob([bytes])),f.sha256);}}const attackPng=await zip.file(rootPath+manifest.clips.attack.directions.S.frames[0].file).async('nodebuffer'),paint=canvas();paint.width=1000;paint.height=360;paint.getContext('2d').drawImage(await loadImage(attackPng),0,0);const rgba=paint.getContext('2d').getImageData(0,0,1000,360).data;let bbox=[1000,360,-1,-1];for(let y=0;y<360;y++)for(let x=0;x<1000;x++)if(rgba[(y*1000+x)*4+3]>128){bbox=[Math.min(bbox[0],x),Math.min(bbox[1],y),Math.max(bbox[2],x),Math.max(bbox[3],y)];}assert.deepEqual(bbox,[200,36,799,323]);
ok('Source Pack v6 contains actual transformed PNGs, shared per-clip output canvases/roots, scale-once physical mapping and hashes');
const legacy=C.initialize({...main,settings:{...S.defaults(),anchorX:128,anchorY:224,rangeEnd:0,directionMode:'billboard'},extraClips:{small:{canvas:[256,256],frames:idle.frames,timing:p.extraClips.idle.timing,directions:{}}}}); // Use a historically fitting frame for shared-canvas migration.
legacy.extraClips.small.frames=(await sequence(32,64,'old')).frames;const oldzip=await JSZip.loadAsync(await(await P.save(legacy,sig,progress)).arrayBuffer()),meta=JSON.parse(await oldzip.file('project.json').async('string'));meta.schemaVersion=4;delete meta.placements;delete meta.placementVersion;delete meta.extraClips.small.canvas;for(const k of ['widthPercent','heightPercent','shapeLinked','offsetXUnits','offsetYUnits'])delete meta.settings[k];oldzip.file('project.json',JSON.stringify(meta));const migrated=await P.reopen(await oldzip.generateAsync({type:'blob'}),sig,progress);assert.deepEqual(Array.from(C.canvas(migrated,'small')),[256,256]);near(G.resolve(migrated,'small').anchorY,224);near(G.metrics(migrated,'small').factors[0],.5);assert.equal(G.resolve(migrated,'small').inherited,true);ok('Legacy shared-canvas clips migrate without recalibrating roots, dimensions or scale');
const existing=await P.reopen(new Blob([fs.readFileSync('sprite-forge/evidence/a4-project.spriteforge.zip')]),sig,progress);assert.equal(existing.audio.neutral_quips.takes.length,2);assert.equal(G.resolve(existing,existing.settings.clipId).widthPercent,100);ok('Existing A4 audio project reopens with identity shape and intact sound banks');
fs.writeFileSync('sprite-forge/evidence/a3-placement-regression.spriteforge.zip',Buffer.from(await saved.arrayBuffer()));fs.writeFileSync('sprite-forge/evidence/a3-placement_source_pack_v6.zip',Buffer.from(await source.arrayBuffer()));fs.writeFileSync('sprite-forge/evidence/a3-placement-regression.json',JSON.stringify({version:'0.6.0',checks,browserAcceptance:false,method:'Native Canvas/ZIP, actual PNG bytes and renderer geometry; explicit fake Web Audio for old PCM project.'},null,2)+'\n');console.log(checks.join('\n'));
})().catch(e=>{console.error(e);process.exit(1)});
