// Pure state-owned animation clocks and simulation parity. No browser/audio device.
const assert=require('node:assert/strict'),fs=require('node:fs'),{sandbox,load}=require('./audio-test-runtime.cjs'),s=sandbox();
const SF=load(s,['timeline','store','clips','placement','simulator','playback']),{Playback:P,Clips:C,Timeline:T,Store:S,Simulator:Sim}=SF,json=x=>JSON.parse(JSON.stringify(x)),near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`),checks=[],ok=x=>checks.push(x);
const frames=(prefix,n)=>Array.from({length:n},(_,i)=>({name:prefix+'_'+i+'.png',sha256:(i+1).toString(16).padStart(64,'0'),blob:new Blob(),width:16,height:16})),timing=(n,fps)=>({sourceFps:fps,displayFps:fps,playbackSpeedPercent:100,playbackMode:'forward_loop',rangeStart:0,rangeEnd:n-1});
const p=C.initialize({settings:{...S.defaults(),...timing(8,8),anchorX:8,anchorY:16},canvas:[16,16],frames:frames('main',8),issues:[],extraClips:{idle:{canvas:[16,16],frames:frames('idle',3),directions:{},timing:timing(3,5)},attack:{canvas:[16,16],frames:frames('attack',5),directions:{},timing:{...timing(5,10),rangeStart:1}}},stateClips:{neutral_idle:'idle',neutral_roam:'idle',hostile_attack:'attack',companion_combat:'attack'}});
const bind=(state,patch)=>p.statePlayback[state]={...P.defaults(),...patch};
P.validate(p);const e=P.create();e.enter(p,'neutral_idle',5,1);assert.equal(e.snapshot(p,5,2.2).frame,T.at(C.timing(p,'idle'),2.2));e.enter(p,'neutral_roam',5.2,2);assert.equal(e.snapshot(p,5.2,2.4).frame,T.at(C.timing(p,'idle'),2.4));bind('neutral_idle',{policy:'restart'});e.enter(p,'neutral_idle',6,3);assert.equal(e.snapshot(p,6,99).frame,0);assert.equal(e.snapshot(p,6.4,99).frame,2);e.enter(p,'neutral_idle',7,4);assert.equal(e.snapshot(p,7,99).frame,0);ok('Legacy Continue preserves shared phase; Restart uses state-entry time, including same-state re-entry');
bind('hostile_attack',{policy:'once_return',returnClip:'idle',marker:P.setMarker(p,'hostile_attack',2)});e.enter(p,'hostile_attack',10,5);assert.equal(e.snapshot(p,10,10).phase,'return');e.trigger(p,10.2);let v=e.snapshot(p,10.2,22);assert.equal(v.clipId,'attack');assert.equal(v.frame,1);near(v.remainingSeconds,.4);e.tick(p,10.35);assert.equal(e.snapshot(p,10.35,22).frame,2);assert.equal(e.log.filter(x=>x.type==='marker').length,1);e.tick(p,10.599);assert.equal(e.snapshot(p,10.599,22).phase,'action');e.tick(p,10.6);v=e.snapshot(p,10.6,22);assert.equal(v.phase,'return');assert.equal(v.clipId,'idle');assert.equal(v.frame,T.at(C.timing(p,'idle'),22));ok('Attack actions wait for actual trigger, start at range start and return at exact duration to ongoing idle phase');
e.trigger(p,11);e.trigger(p,11.2);near(e.snapshot(p,11.2,22).remainingSeconds,.4);bind('hostile_attack',{policy:'once_return',returnClip:'idle',retrigger:'ignore'});e.reset(p,'hostile_attack',12,6);e.trigger(p,12);assert.equal(e.trigger(p,12.2),false);near(e.snapshot(p,12.2,22).remainingSeconds,.2);bind('hostile_attack',{policy:'once_return',returnClip:'idle',retrigger:'queue'});e.reset(p,'hostile_attack',13,7);e.trigger(p,13);for(let i=0;i<30;i++)e.trigger(p,13.2);assert.equal(e.snapshot(p,13.2,22).queued,true);e.tick(p,13.4);assert.equal(e.snapshot(p,13.4,22).frame,1);assert.equal(e.snapshot(p,13.4,22).queued,false);e.tick(p,13.8);assert.equal(e.snapshot(p,13.8,22).phase,'return');assert.equal(e.log.filter(x=>x.type==='start').length,2);ok('Restart/Ignore/Queue one policies behave predictably; repeated queue requests cannot accumulate unbounded actions');
e.reset(p,'hostile_attack',14,8);e.trigger(p,14);e.trigger(p,14.1);e.enter(p,'defeat_transition',14.2,9);e.tick(p,50);assert.equal(e.snapshot(p,50,22).phase,'state');assert.equal(e.snapshot(p,50,22).queued,false);assert.equal(e.log.filter(x=>x.type==='start').length,1);bind('deploying',{policy:'once_return'});e.enter(p,'deploying',51,10);assert.equal(e.snapshot(p,51,22).phase,'action');e.enter(p,'stored',51.1,11);assert.equal(e.snapshot(p,51.1,22).phase,'state');ok('Defeat/pickup/deployment exits cancel the active action and queue; non-attack actions trigger on entry without changing behavior state');
bind('hostile_attack',{policy:'once_return',returnClip:'idle',marker:P.setMarker(p,'hostile_attack',2)});p.extraClips.attack.timing.displayFps=1;e.reset(p,'hostile_attack',0,20,true);e.tick(p,.15);assert.equal(e.snapshot(p,.15,0).frame,1);assert.equal(e.log.filter(x=>x.type==='marker').length,1);near(P.marker(p,'hostile_attack').firstPassSeconds,.1);p.extraClips.attack.timing.displayFps=120;e.reset(p,'hostile_attack',0,21,true);e.tick(p,.4);assert.equal(e.snapshot(p,.4,0).phase,'return');p.extraClips.attack.timing.playbackMode='ping_pong';p.extraClips.attack.timing.displayFps=10;e.reset(p,'hostile_attack',0,22,true);const seen=[];for(let i=0;i<6;i++){e.tick(p,i/10);seen.push(e.snapshot(p,i/10,0).frame);}assert.deepEqual(seen,[1,2,3,4,3,2]);e.tick(p,.6);assert.equal(e.snapshot(p,.6,0).phase,'return');p.extraClips.attack.timing.playbackSpeedPercent=200;near(P.contract(p).bindings.hostile_attack.cycleDurationSeconds,.3);ok('Display FPS never changes action completion/marker time; one authored ping-pong cycle retains exact endpoints; speed controls action duration');
p.extraClips.attack.timing={...timing(5,10),rangeStart:1};e.reset(p,'hostile_attack',0,23,true);e.seek(p,.25,0);assert.equal(e.snapshot(p,0,99).frame,3);assert.equal(e.snapshot(p,0,99).queued,false);near(e.snapshot(p,0,99).remainingSeconds,.15);e.tick(p,.15);assert.equal(e.snapshot(p,.15,99).phase,'return');bind('neutral_idle',{policy:'restart'});e.enter(p,'neutral_idle',1,24);e.seek(p,.4,1);assert.equal(e.snapshot(p,1,99).frame,2);ok('Paused local clock and scrubbing/stepping resume an action/state at the inspected phase without seeking ongoing global phase');
const old=p.statePlayback.hostile_attack.marker;p.extraClips.attack.frames=[...p.extraClips.attack.frames].reverse();P.remapMarkers(p);assert.equal(p.statePlayback.hostile_attack.marker.frame,2);p.extraClips.attack.frames[2]={...p.extraClips.attack.frames[2],sha256:'a'.repeat(64)};assert.equal(P.marker(p,'hostile_attack').reason,'source_changed');P.validate(p);p.extraClips.attack.frames[2]={...p.extraClips.attack.frames[2],sha256:old.sha256};p.extraClips.attack.timing.rangeStart=3;assert.equal(P.marker(p,'hostile_attack').reason,'outside_range');p.extraClips.attack.timing.rangeStart=0;p.statePlayback.hostile_attack.marker=null;assert.throws(()=>P.validate({...p,statePlayback:{neutral_idle:{...P.defaults(),returnClip:'ghost'}}}),/binding/);ok('Strike markers bind to source identity, flag changed footage/out-of-range poses and never create gameplay events; invalid return bindings fail');
S.replace(p);S.commitPlayback(()=>bind('neutral_idle',{policy:'once_return',returnClip:'attack'}));S.history(false);assert.equal(P.binding(p,'neutral_idle').policy,'restart');S.history(true);assert.equal(P.binding(p,'neutral_idle').policy,'once_return');S.commit({clipId:'main_clip'});S.commitPlayback(()=>bind('deploying',{policy:'once_return',returnClip:'main_clip'}));S.commit({clipId:'main_renamed'});assert.equal(P.binding(p,'deploying').returnClip,'main_renamed');assert.throws(()=>S.commitPlayback(()=>bind('deploying',{policy:'bogus'})),/binding/);assert.equal(P.binding(p,'deploying').policy,'once_return');ok('Playback edits participate in general Undo/Redo/rollback; main renaming updates explicit return references');
// Observe identical seeded encounters under different visual schedules; the engine has no simulator mutations.
const run=fps=>{const game=Sim.create(p.simulation),r=P.create();p.extraClips.attack.timing={...timing(5,fps),displayFps:Math.min(120,fps*2)};let cursor=0;for(let i=0;i<1200;i++){game.step(1/60,{},true);const m=game.model;r.enter(p,m.state,m.timeSeconds,m.entryId);r.tick(p,m.timeSeconds);for(const event of m.events)if(event.id>cursor){cursor=event.id;if(event.type==='attack'&&event.state===m.state&&event.entryId===m.entryId)r.trigger(p,event.timeSeconds);}r.snapshot(p,m.timeSeconds,m.timeSeconds);}return json(game.model);};assert.deepEqual(run(2),run(120));ok('Seeded gameplay HP, attacks, movement, state entries and event IDs are identical at 2 vs 120 source FPS');
fs.writeFileSync('sprite-forge/evidence/a3-playback-checks.json',JSON.stringify({version:'0.6.0',checks,freshBrowserAcceptance:false,method:'Pure playback clocks, exact timing contracts and unchanged seeded simulator state; no browser/audio device.'},null,2)+'\n');console.log(checks.join('\n'));
