// Static bundle/package integrity; no browser is opened.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto'),JSZip=require('../vendor/jszip.min.js');
const root='sprite-forge/',read=p=>fs.readFileSync(root+p),hash=b=>crypto.createHash('sha256').update(b).digest('hex');
(async()=>{const html=read('SpriteForge.html'),text=html.toString(),modules=['timeline','store','banks','media','clips','placement','corrections','directions','audio','simulator','playback','renderer','pack','app','studio','keyer','action-controls'];
for(const module of modules){const source=read('src/'+module+'.js').toString();new vm.Script(source);assert.ok(text.includes(source.replace(/<\/script/gi,'<\\/script')),'bundled source: '+module);}
const scripts=[...text.matchAll(/<script>([\s\S]*?)<\/script>/g)];assert.equal(scripts.length,2);for(const m of scripts)new vm.Script(m[1]);assert.ok(!/\/\*(STYLE|VENDOR|APP)\*\//.test(text));assert.ok(!/<(?:script|link)[^>]+(?:src|href)=/i.test(text));assert.match(text,/connect-src 'none'/);assert.match(text,/font-src 'none'/);
const ids=[...text.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size,'unique control IDs');
const trial=read('SpriteForge-Trial.zip'),zip=await JSZip.loadAsync(trial,{checkCRC32:true});assert.deepEqual(await zip.file('SpriteForge-Trial/SpriteForge.html').async('nodebuffer'),html);assert.deepEqual(read('SpriteForge-Trial/SpriteForge.html'),html);for(const [source,target] of [['TRIAL-README.txt','README.txt'],['FEATURE-GUIDE.md','FEATURE-GUIDE.md'],['ALPHA-HANDOFF.md','ALPHA-HANDOFF.md']])assert.deepEqual(await zip.file('SpriteForge-Trial/'+target).async('nodebuffer'),read(source));
const result={version:'0.6.2',htmlBytes:html.length,trialZipBytes:trial.length,htmlSha256:hash(html),trialZipSha256:hash(trial),packagedHtmlMatches:true,sourceModules:modules.length,sourceSyntax:true,bundleSyntax:true,uniqueControlIds:ids.length,staticGrain:true,goldInk:'#e7bc72',externalFontDownloads:0,priorMilestoneBrowserChecks:41,currentBrowserAcceptance:false,currentVerification:'Source-facing actual controls/save-reopen/legacy/runtime export policy and camera-relative rooted mirror checks with mock DOM/native Canvas; stationary target tracking; A3 state-owned clocks/attack events/returns/queues/cancellation and A2 correction/interpolation/source identity/PNG/archive mapping and per-clip renderer and full App/Studio/action controls with mock DOM/native Canvas; pure bank scheduler and mocked Web Audio; native media and real Salvatore front reopen; existing timeline/reference/encounter suites; standalone bundle/package integrity.',note:'Local file browser control blocked; save then refresh manually. Historical browser results are from 0.2.0.'};fs.writeFileSync(root+'evidence/release-integrity.json',JSON.stringify(result,null,2)+'\n');console.log(`Release integrity: ${modules.length} modules and bundled scripts parse; ${ids.length} unique controls; embedded local assets/CSP; packaged HTML/docs match; SHA-256 recorded.`);
})().catch(e=>{console.error(e);process.exit(1)});
