// Sequential isolated processes keep native/large-raster memory bounded.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{spawn,execFileSync}=require('node:child_process'),Test=require('./config.cjs');
const mandatory=['timeline','reference','simulator','playback','bank-scheduler','audio-loop-policy','placement','placement-controls','corrections','keyer-controls','playback-controls','bank-controls','bank-persistence','media-formats','source-facing','bundle'];
const native=['placement','placement-controls','corrections','keyer-controls','playback-controls','bank-controls','bank-persistence','media-formats','source-facing','historical-archives','emet-corrections'];
const groups={external:['historical-archives','emet-corrections','salvatore-directions'],browser:['smoke','shell'],package:['release'],'legacy-browser':['browser','milestone2']};
const args=process.argv.slice(2),selected=[],results=[];
if(args.includes('--help')){console.log('node tests/run.cjs [--external] [--browser] [--package] [--legacy-browser] [--suite NAME]\nDefault: 16 mandatory self-contained suites. Optional groups are explicit; missing inputs/dependencies are BLOCKED (exit 2). Failures exit 1. See tests/README.md.');process.exit(0);}
for(let i=0;i<args.length;i++){const arg=args[i];if(arg==='--suite'){const name=args[++i];if(![...mandatory,...Object.values(groups).flat()].includes(name))throw Error('Unknown suite: '+name);selected.push(name);}else if(arg.startsWith('--')&&groups[arg.slice(2)])selected.push(...groups[arg.slice(2)]);else throw Error('Unknown argument: '+arg);}
const suites=[...new Set(args.includes('--suite')?selected:[...mandatory,...selected])];
function needs(name){const missing=[];const dependencies=[];if(native.includes(name))dependencies.push('@napi-rs/canvas');if(name==='media-formats')dependencies.push('sharp');if(['smoke','shell','browser','milestone2','salvatore-directions'].includes(name))dependencies.push('playwright');for(const dep of dependencies){try{Test.dependency(dep);}catch(e){missing.push(dep+': '+e.message.split('\n')[0]);}}
 const envFiles={ 'emet-corrections':['SPRITE_FORGE_EMET'], 'salvatore-directions':['SPRITE_FORGE_SALVATORE_DIRECTIONS'], browser:['SPRITE_FORGE_SALVATORE'],milestone2:['SPRITE_FORGE_SALVATORE'] };
 for(const variable of envFiles[name]||[]){const value=process.env[variable];if(!value||!fs.existsSync(value)||!fs.statSync(value).isDirectory())missing.push('configure existing directory '+variable);}
 if(name==='emet-corrections'&&process.env.SPRITE_FORGE_EMET&&fs.existsSync(process.env.SPRITE_FORGE_EMET)&&fs.statSync(process.env.SPRITE_FORGE_EMET).isDirectory()&&fs.readdirSync(process.env.SPRITE_FORGE_EMET).filter(n=>/\.png$/i.test(n)).length<3)missing.push('Emet requires at least three PNG frames');
 if(name==='salvatore-directions'&&process.env.SPRITE_FORGE_SALVATORE_DIRECTIONS){for(const dir of ['S','SE','E','NE','N','NW','W','SW'])if(!fs.existsSync(path.join(process.env.SPRITE_FORGE_SALVATORE_DIRECTIONS,dir)))missing.push('missing direction '+dir);}
 if(name==='historical-archives')for(const file of ['legacy-v1.spriteforge.zip','fixture.spriteforge.zip','salvatore_front.spriteforge.zip','a4-project.spriteforge.zip'])if(!fs.existsSync(Test.archivePath(file)))missing.push('missing archive '+Test.archivePath(file));
 if(name==='release')for(const file of ['SpriteForge-Trial.zip','SpriteForge-Trial/SpriteForge.html'])if(!fs.existsSync(Test.projectPath(file)))missing.push('missing packaged artifact '+file);
 if(['smoke','shell','browser','milestone2','salvatore-directions'].includes(name)&&process.env.SPRITE_FORGE_BROWSER&&!fs.existsSync(process.env.SPRITE_FORGE_BROWSER))missing.push('missing SPRITE_FORGE_BROWSER executable');
 if(name==='shell'){try{execFileSync('git',['cat-file','-e','cdb4d63498b3a1195c0effcc8bbf73a66f773ef5:src/index.html'],{cwd:Test.root,stdio:'ignore'});}catch{missing.push('shell control-contract baseline requires Git and repository history through cdb4d63 (fetch history for a shallow clone)');}}
 return missing;
}
function execute(name){return new Promise(resolve=>{const started=Date.now(),outDir=Test.outputPath(name);fs.mkdirSync(outDir,{recursive:true});const child=spawn(process.execPath,[Test.projectPath('tests',name+'.cjs')],{cwd:Test.root,env:{...process.env,SPRITE_FORGE_TEST_OUTPUT:outDir},windowsHide:true});let stdout='',stderr='',timedOut=false;child.stdout.on('data',b=>stdout+=b);child.stderr.on('data',b=>stderr+=b);const timer=setTimeout(()=>{timedOut=true;child.kill();},180000);child.on('error',e=>stderr+='\n'+e.stack);child.on('close',code=>{clearTimeout(timer);fs.writeFileSync(Test.outputPath(name+'.log'),stdout+stderr);resolve({name,status:code===0&&!timedOut?'pass':'fail',exitCode:code,seconds:(Date.now()-started)/1000,reason:timedOut?'180-second timeout':code===0?undefined:stderr.trim().slice(0,3000)});});});}
(async()=>{for(const name of suites){const missing=needs(name);const result=missing.length?{name,status:'blocked',reason:missing.join('; ')}:await execute(name);if(result.status==='fail'&&/Executable doesn't exist|Chromium distribution[^\n]*not found|executable doesn't exist|Failed to launch[^\n]*ENOENT/i.test(result.reason||''))result.status='blocked';results.push(result);console.log(result.status.toUpperCase()+' '+name+(result.seconds?' ('+result.seconds.toFixed(2)+'s)':'')+(result.reason?' — '+result.reason.split('\n')[0]:''));}
const hashes={};for(const file of ['SpriteForge.html','Claude outputs/SpriteForge-0.7-preview.html'])hashes[file]=crypto.createHash('sha256').update(fs.readFileSync(Test.projectPath(file))).digest('hex');
const dependencies={};for(const dep of ['@napi-rs/canvas','sharp','playwright']){try{dependencies[dep]=process.env.SPRITE_FORGE_NODE_MODULES?require(path.join(path.resolve(process.env.SPRITE_FORGE_NODE_MODULES),dep,'package.json')).version:require(dep+'/package.json').version;}catch{dependencies[dep]='unavailable';}}
const report={createdAt:new Date().toISOString(),platform:process.platform,node:process.version,root:Test.root,outputRoot:Test.outputRoot,artifacts:hashes,dependencies,results,notRequested:Object.entries(groups).filter(([flag])=>!args.includes('--'+flag)&&!groups[flag].some(n=>suites.includes(n))).map(([flag])=>flag),browserAcceptance:false,humanListening:false};
fs.writeFileSync(Test.outputPath('results.json'),JSON.stringify(report,null,2)+'\n');console.log('Report: '+Test.outputPath('results.json'));process.exitCode=results.some(r=>r.status==='fail')?1:results.some(r=>r.status==='blocked')?2:0;
})().catch(e=>{console.error(e);process.exitCode=1;});
