// Actual controls and archive pipeline with explicit DOM mocks/native Canvas, no browser navigation.
const assert=require('node:assert/strict'),fs=require('node:fs'),{s,SF,n,flush,settle,load}=require('./control-test-runtime.cjs'),JSZip=require('../vendor/jszip.min.js');
const sig={cancelled:false},progress=()=>{};
(async()=>{load(s,['app','studio','keyer','action-controls']);await flush();n('action-demo').click();await settle();n('accept').click();const p=SF.Store.project,main=p.settings.clipId,id='action_attack';
 n('active-clip').value=id;n('active-clip').onchange();n('source-facing').value='right';n('source-facing').onchange();assert.equal(p.clipFacing[id],'right');assert.equal(SF.Directions.sourceFacing(p,main),'views');
 SF.Store.history(false);assert.equal(SF.Directions.sourceFacing(p,id),'views');SF.Store.history(true);assert.equal(p.clipFacing[id],'right');
 for(const [source,facing,orbit,mirror] of [['right',90,0,false],['right',-90,0,true],['left',90,0,true],['left',-90,0,false],['right',90,180,true],['right',0,0,false],['left',0,0,false]]){p.clipFacing[id]=source;const r=SF.Directions.encounter(p,id,'NW',facing,orbit);assert.equal(r.recipe.mirror,mirror);assert.equal(r.recipe.widthFactor,1);assert.equal(r.recipe.rearDarknessPercent,0);assert.equal(r.direction,'S');assert.equal(r.frames,p.extraClips[id].frames);}
 p.clipFacing[id]='right';const baseline=SF.Directions.resolve(p,id,'NW');p.clipFacing[id]='views';assert.equal(SF.Directions.encounter(p,id,'NW',-90).recipe.mirror,baseline.recipe.mirror);p.clipFacing[id]='right';
 // Draw a source point on the root; both mirror signs preserve its exact screen position.
 const transform=[];const ctx={save(){},restore(){},translate(x,y){transform.push(['translate',x,y]);},scale(x,y){transform.push(['scale',x,y]);},drawImage(...args){transform.push(['image',...args.slice(1)]);}};
 const f={proxy:{width:80,height:100},width:80,height:100};for(const facing of [90,-90]){transform.length=0;SF.Directions.draw(ctx,f,[23,91],250,300,[2,3],SF.Directions.encounter(p,id,'S',facing).recipe);assert.deepEqual(transform[0],['translate',250,300]);assert.deepEqual(transform[1],['scale',facing===90?2:-2,3]);assert.deepEqual(transform[2],['image',-23,-91,80,100]);}
 // Stationary combat turns when its target crosses around it, without requiring pursuit.
 const config=p.simulation,sim=SF.Simulator.create(config);Object.assign(sim.model.actor,{x:0,z:0});Object.assign(sim.model.player,{x:20,z:0});sim.step(1/60);assert.equal(sim.model.state,'hostile_attack');assert.equal(sim.model.facing,90);sim.model.player.x=-20;sim.step(1/60);assert.equal(sim.model.facing,-90);assert.equal(sim.model.actor.x,0);
 sim.gallery('companion_combat');Object.assign(sim.model.enemy,{x:20,z:0,hp:80,active:true});sim.step(1/60);assert.equal(sim.model.facing,90);sim.model.enemy.x=-20;sim.step(1/60);assert.equal(sim.model.facing,-90);
 SF.Store.commitFacing(main,'left');SF.Store.commit({clipId:'renamed_main'});assert.equal(p.clipFacing.renamed_main,'left');assert.equal(p.clipFacing[main],undefined);SF.Store.history(false);assert.equal(p.clipFacing[main],'left');
 const blob=await SF.Pack.save(p,sig,progress),reopened=await SF.Pack.reopen(new s.File([blob],'facing.spriteforge.zip'),sig,progress);assert.equal(reopened.clipFacing[id],'right');assert.equal(reopened.clipFacing[main],'left');
 const z=await JSZip.loadAsync(await blob.arrayBuffer()),meta=JSON.parse(await z.file('project.json').async('string'));delete meta.clipFacing;z.file('project.json',JSON.stringify(meta));const old=await SF.Pack.reopen(new s.File([await z.generateAsync({type:'uint8array'})],'old.zip'),sig,progress);assert.equal(SF.Directions.sourceFacing(old,id),'views');
 meta.clipFacing={[id]:'up'};z.file('project.json',JSON.stringify(meta));const invalid=await z.generateAsync({type:'uint8array'});await assert.rejects(()=>SF.Pack.reopen(new s.File([invalid],'invalid.zip'),sig,progress),/source facing/);
 const pack=await SF.Pack.source(p,sig,progress),zip=await JSZip.loadAsync(await pack.arrayBuffer()),path=Object.keys(zip.files).find(x=>x.endsWith('/manifest.json')),manifest=JSON.parse(await zip.file(path).async('string'));assert.equal(manifest.clips[id].sourceFacing,'right');assert.equal(manifest.clips[id].facingPolicy,'runtime_source_mirror_toward_target_about_root');
 console.log('Source facing: actual control, per-clip independence, Undo/Redo/rename, camera-relative mirroring, anchored draw, stationary target tracking, save/reopen, legacy defaults, invalid archive and Source Pack contract passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
