// Source-frame correction tracks; preview clock and authored physical sizing stay separate.
SF.Corrections = (() => {
  const fields=['offsetX','offsetY','scalePercent','pivotX','pivotY'],modes=['linear','hold','smooth'],cache=new WeakMap(),revisions=new WeakMap();
  const identity=g=>({offsetX:0,offsetY:0,scalePercent:100,pivotX:g.anchorX,pivotY:g.anchorY,interpolation:'linear'});
  function initialize(p){p.corrections??={};p.correctionVersion=1;return p;}
  const empty=()=>({enabled:true,keys:[],review:[]});
  const profile=(p,id)=>{initialize(p);return Object.hasOwn(p.corrections,id)?p.corrections[id]:{outputMode:'expand',tracks:{}};};
  const track=(p,id,dir='S')=>profile(p,id).tracks[dir]||empty();
  function frames(p,id,dir='S'){const c=SF.Clips.get(p,id);return dir==='S'?c.frames:c.directions?.[dir]?.frames||[];}
  function direction(p,id,dir){const r=SF.Directions.resolve(p,id,dir);return r.recipe||r.direction==='S'?'S':dir;}
  const usable=t=>t.enabled&&!t.review?.length;
  function resolvedTrack(p,id,dir){const t=track(p,id,dir);return t.link==='S'&&usable(t)?track(p,id,'S'):t;}
  function numeric(k){for(const [field,min,max] of [['offsetX',-8192,8192],['offsetY',-8192,8192],['scalePercent',1,1000],['pivotX',0,8192],['pivotY',0,8192]])if(!Number.isFinite(k[field])||k[field]<min||k[field]>max)throw Error(`Invalid correction ${field}: expected ${min}–${max}.`);if(!modes.includes(k.interpolation))throw Error('Unknown correction interpolation.');}
  function validate(p){initialize(p);const ids=SF.Clips.ids(p);let total=0;for(const [id,c]of Object.entries(p.corrections)){if(!ids.includes(id)||!c||!['expand','clip'].includes(c.outputMode)||!c.tracks||typeof c.tracks!=='object'||Array.isArray(c.tracks))throw Error('Invalid correction clip profile.');for(const [dir,t]of Object.entries(c.tracks)){if(!SF.Directions.order.includes(dir)||!t||typeof t.enabled!=='boolean'||!Array.isArray(t.keys)||!Array.isArray(t.review)||t.keys.length+t.review.length>2000||t.link!==undefined&&(t.link!=='S'||dir==='S'||t.keys.length||t.review.length))throw Error('Invalid correction track.');let last=-1;const source=frames(p,id,dir);for(const k of t.keys){numeric(k);if(!Number.isInteger(k.frame)||k.frame<=last||k.frame>=source.length||k.frame<0||k.sha256!==source[k.frame].sha256||k.name!==source[k.frame].name)throw Error('Correction key does not match its source frame.');last=k.frame;}for(const k of t.review){numeric(k);if(!Number.isInteger(k.frame)||k.frame<0||k.frame>=2000||typeof k.name!=='string'||k.name.length>500||!/^([a-f0-9]{64})$/.test(k.sha256))throw Error('Invalid correction review key.');}total+=t.keys.length+t.review.length;}}
    if(total>4000)throw Error('Correction keys and retained review keys exceed the project limit of 4,000.');return p;}
  function evaluate(p,id,index,dir='S'){const g=SF.Placement.resolve(p,id),t=resolvedTrack(p,id,dir),keys=usable(t)?t.keys:[];if(!keys.length)return identity(g);if(index<=keys[0].frame)return {...keys[0]};if(index>=keys.at(-1).frame)return {...keys.at(-1)};let lo=0,hi=keys.length-1;while(hi-lo>1){const mid=(lo+hi)>>1;if(keys[mid].frame<=index)lo=mid;else hi=mid;}const a=keys[lo],b=keys[hi];if(index===a.frame||a.interpolation==='hold')return {...a};let f=(index-a.frame)/(b.frame-a.frame);if(a.interpolation==='smooth')f=f*f*(3-2*f);return {...Object.fromEntries(fields.map(k=>[k,a[k]+(b[k]-a[k])*f])),interpolation:a.interpolation};}
  function affine(k){const q=k.scalePercent/100;return {scale:q,x:(1-q)*k.pivotX+k.offsetX,y:(1-q)*k.pivotY-k.offsetY};}
  function matrix(p,id,index,dir,layout){const k=evaluate(p,id,index,direction(p,id,dir)),a=affine(k),r=SF.Directions.resolve(p,id,dir).recipe,fx=layout.shape[0]*(r?.widthFactor??1)*(r?.mirror?-1:1),fy=layout.shape[1];return [fx*a.scale,0,0,fy*a.scale,layout.anchor[0]+fx*(a.x-layout.sourceAnchor[0]),layout.anchor[1]+fy*(a.y-layout.sourceAnchor[1])];}
  function own(p,id,dir){initialize(p);if(!Object.hasOwn(p.corrections,id))p.corrections[id]={outputMode:'expand',tracks:{}};const c=p.corrections[id];return c.tracks[dir]??=empty();}
  function changed(p){cache.delete(p);revisions.set(p,(revisions.get(p)||0)+1);}
  function upsert(p,id,index,dir,k){numeric(k);const f=frames(p,id,dir)[index];if(!f)throw Error('No source frame at this index.');const t=own(p,id,dir);if(t.link)throw Error('Unlink this view before editing its keys.');if(t.review.length)throw Error('Resolve unmatched keys before editing this track.');t.keys=t.keys.filter(k=>k.frame!==index);t.keys.push({...Object.fromEntries(fields.map(field=>[field,k[field]])),interpolation:k.interpolation,frame:index,sha256:f.sha256,name:f.name});t.keys.sort((a,b)=>a.frame-b.frame);t.enabled=true;changed(p);}
  function remap(p,id,dir){const t=profile(p,id).tracks[dir];if(!t||t.link)return;const source=frames(p,id,dir),keys=[...t.keys,...t.review],matched=[],review=[],used=new Set();for(const k of keys){let candidates=source.map((f,i)=>f.sha256===k.sha256&&f.name===k.name?i:-1).filter(i=>i>=0);if(!candidates.length)candidates=source.map((f,i)=>f.sha256===k.sha256?i:-1).filter(i=>i>=0);if(candidates.length===1&&!used.has(candidates[0])){const i=candidates[0];used.add(i);matched.push({...k,frame:i,name:source[i].name,sha256:source[i].sha256});}else review.push(k);}t.keys=matched.sort((a,b)=>a.frame-b.frame);t.review=review;changed(p);}
  function remapAll(p){initialize(p);for(const [id,c]of Object.entries(p.corrections)){if(!SF.Clips.ids(p).includes(id)){delete p.corrections[id];continue;}for(const dir of Object.keys(c.tracks))remap(p,id,dir);}changed(p);}
  function requestedViews(p,id){const c=SF.Clips.get(p,id);return p.settings.directionMode==='billboard'?['S']:p.settings.directionMode==='generated'?SF.Directions.order:['S',...Object.keys(c.directions||{})];}
  function layout(p,id,strict=true){const g=SF.Placement.resolve(p,id),c=SF.Clips.get(p,id),signature=JSON.stringify([g,p.settings.directionMode,p.settings.generatedSideWidthPercent,p.settings.rearDarknessPercent,p.settings.mirrorDirections]),bucket=cache.get(p)||new Map(),old=bucket.get(id);let out=old?.signature===signature&&old.frames===c.frames&&old.directions===c.directions?old.out:null;
    if(!out){const views=requestedViews(p,id),base=SF.Placement.output(p,id,views.map(d=>SF.Directions.resolve(p,id,d).recipe),false);let left=-base.anchor[0],right=base.canvas[0]-base.anchor[0],top=-base.anchor[1],bottom=base.canvas[1]-base.anchor[1];for(const dir of views){const sourceDir=direction(p,id,dir),t=resolvedTrack(p,id,sourceDir);if(!usable(t)||!t.keys.length)continue;const r=SF.Directions.resolve(p,id,dir).recipe,fx=base.shape[0]*(r?.widthFactor??1)*(r?.mirror?-1:1),fy=base.shape[1];for(let i=0;i<SF.Clips.get(p,id).frames.length;i++){const a=affine(evaluate(p,id,i,sourceDir)),x0=(a.x-g.anchorX)*fx,x1=(g.canvas[0]*a.scale+a.x-g.anchorX)*fx,y0=(a.y-g.anchorY)*fy,y1=(g.canvas[1]*a.scale+a.y-g.anchorY)*fy;left=Math.min(left,x0,x1);right=Math.max(right,x0,x1);top=Math.min(top,y0,y1);bottom=Math.max(bottom,y0,y1);}}
      const expanded=[Math.max(1,Math.ceil(right-left)),Math.max(1,Math.ceil(bottom-top))],clipped=profile(p,id).outputMode==='clip';out={...base,canvas:clipped?base.canvas:expanded,anchor:clipped?base.anchor:[-left,-top],expandedCanvas:expanded,outputMode:clipped?'clip':'expand',correctionsBakedIntoPixels:true,wouldCrop:expanded.some((n,i)=>n>base.canvas[i]),baseCanvas:base.canvas,baseAnchor:base.anchor};bucket.set(id,{signature,frames:c.frames,directions:c.directions,out});cache.set(p,bucket);}
    if(strict&&out.canvas.some(n=>n>8192))throw Error(`${id}: corrected output is ${out.canvas.join(' × ')} px (limit 8192). Reduce corrections/shape or choose Crop to base canvas.`);return out;
  }
  function render(p,id,index,dir,factors,original=false,draft=null){const k=original?identity(SF.Placement.resolve(p,id)):draft||evaluate(p,id,index,direction(p,id,dir)),a=affine(k);let clip=null;if(!original&&profile(p,id).outputMode==='clip'){const out=layout(p,id,false);clip={left:-out.anchor[0]*factors[0]/out.shape[0],top:-out.anchor[1]*factors[1]/out.shape[1],width:out.canvas[0]*factors[0]/out.shape[0],height:out.canvas[1]*factors[1]/out.shape[1]};}return {...a,clip,key:k};}
  function pending(p){return Object.entries(p.corrections||{}).flatMap(([id,c])=>Object.entries(c.tracks).filter(([,t])=>t.enabled&&t.review.length).map(([dir,t])=>({id,dir,count:t.review.length})));}
  return {fields,modes,initialize,empty,identity,profile,track,frames,direction,usable,resolvedTrack,numeric,validate,evaluate,affine,matrix,own,changed,upsert,remap,remapAll,requestedViews,layout,render,pending,revision:p=>revisions.get(p)||0};
})();
