SF.Keyer = (() => {
  const $=id=>document.getElementById(id),app=SF.App,store=SF.Store,C=SF.Corrections,p=()=>store.project,id=()=>SF.Studio.clipId;
  let dir='S',draft=null,signature='',drag=null,seamSignature='',previewSignature='';
  function projectChanged(){dir='S';draft=null;signature='';drag=null;seamSignature='';previewSignature='';p().preview.correctionView??='corrected';}
  const original=()=>p().preview.correctionView==='original';
  const current=()=>app.frame();
  function cleanDraft(){const k=C.evaluate(p(),id(),current(),dir);draft={id:id(),dir,index:current(),key:{...Object.fromEntries([...C.fields,'interpolation'].map(f=>[f,k[f]]))},dirty:false};}
  function refresh(index=current()){
    const has=p().frames.length>0,shown=SF.Studio.visual().direction,shownSignature=id()+'|'+shown;if(SF.Studio.mode==='workbench'&&previewSignature!==shownSignature){dir=C.direction(p(),id(),shown);previewSignature=shownSignature;}const clip=SF.Clips.get(p(),id()),views=['S',...new Set([...Object.keys(clip.directions||{}),...Object.keys(C.profile(p(),id()).tracks)])];if(!views.includes(dir))dir='S';
    options($('correction-view'),views.map(v=>({value:v,label:v==='S'?'Source/front · also used by generated views':v+(clip.directions?.[v]?' · imported':' · missing view (review)')})),dir);
    const t=C.track(p(),id(),dir),linked=!!t.link,available=C.frames(p(),id(),dir).length>0,keys=C.resolvedTrack(p(),id(),dir).keys,readonly=app.busy||!has||linked||!available||!!t.review.length,nextSignature=[id(),dir,index,C.revision(p()),JSON.stringify(SF.Placement.resolve(p(),id()))].join('|');
    if(signature!==nextSignature){signature=nextSignature;cleanDraft();for(const f of [...C.fields,'interpolation'])$('correction-'+f).value=draft.key[f];$('correction-scale-slider').value=draft.key.scalePercent;}
    // Continuous preview redraws must not overwrite a source index being typed.
    if(document.activeElement!==$('correction-frame'))$('correction-frame').value=index;
    $('correction-frame').max=Math.max(0,clip.frames.length-1);$('correction-frame').disabled=app.busy||!has;
    $('correction-view').disabled=app.busy||!has;$('correction-enabled').checked=t.enabled;$('correction-enabled').disabled=app.busy||!has;
    $('correction-link').checked=linked;$('correction-link').disabled=app.busy||!has||dir==='S'||!available;
    for(const f of [...C.fields,'interpolation'])$('correction-'+f).disabled=readonly;$('correction-scale-slider').disabled=readonly;
    options($('correction-list'),[{value:'',label:keys.length+' saved keyframes · choose one'},...keys.map(k=>({value:String(k.frame),label:`${k.frame} · ${k.scalePercent.toFixed(1)}% · ${k.interpolation}`}))],keys.some(k=>k.frame===index)?String(index):'');$('correction-list').disabled=app.busy||!has||!keys.length;
    $('correction-save').disabled=readonly;$('correction-save').textContent=t.keys.some(k=>k.frame===index)?'Update keyframe':'Add keyframe';$('correction-delete').disabled=readonly||!t.keys.some(k=>k.frame===index);
    $('correction-reset').disabled=app.busy||!has;$('correction-revert').disabled=readonly||!draft?.dirty;$('correction-pivot').disabled=readonly;
    $('correction-copy').disabled=app.busy||!has||dir==='S'||!available||!!C.track(p(),id(),'S').review.length;
    $('correction-review').hidden=!t.review.length;$('correction-review').disabled=app.busy||!has;
    $('correction-output').value=C.profile(p(),id()).outputMode;$('correction-output').disabled=app.busy||!has;
    for(const k of ['first','last','original','corrected'])$('correction-'+k).disabled=app.busy||!has;
    $('correction-original').classList.toggle('selected',original());$('correction-corrected').classList.toggle('selected',!original());
    $('correction-drag').disabled=readonly||original()||SF.Studio.mode!=='workbench'||C.direction(p(),id(),shown)!==dir;$('correction-demo').disabled=app.busy;
    $('correction-status').textContent=!has?'Import frames or load the drift test.':t.review.length?`${t.review.length} keyframes need review after a source change. This view’s corrections are paused until reviewed.`:linked?'Shares front-view keyframes. Uncheck Share front-view keyframes to edit a separate copy.':draft.dirty?'Unsaved adjustment. Click Add / Update keyframe to save and apply it.':keys.some(k=>k.frame===index)?`Saved key at source frame ${index}.`:`Source frame ${index} · ${keys.length?'between saved keyframes':'no saved adjustments'}.`;
    $('correction-review-list').textContent=t.review.map(k=>`Old frame ${k.frame}: ${k.name}`).join('\n');
    if(has)try{const out=C.layout(p(),id());$('correction-bounds').textContent=out.outputMode==='clip'?`Original canvas with overflow cropped: ${out.canvas.join(' × ')} px. Full correction bounds: ${out.expandedCanvas.join(' × ')} px${out.wouldCrop?' · outside pixels are clipped.':'.'}`:`Fixed output: ${out.canvas.join(' × ')} px · root ${out.anchor.map(v=>v.toFixed(2)).join(', ')}.`;$('correction-bounds').classList.remove('error');}catch(e){$('correction-bounds').textContent=e.message;$('correction-bounds').classList.add('error');}else $('correction-bounds').textContent='';
    if(has&&$('correction-details').open)seam();
  }
  function options(node,items,selected){const s=JSON.stringify(items);if(node.dataset.items!==s){node.replaceChildren();for(const item of items){const o=document.createElement('option');o.value=item.value;o.textContent=item.label;node.append(o);}node.dataset.items=s;}node.value=selected;}
  function patchDraft(patch,editingField=null){if(!draft||draft.id!==id()||draft.index!==current()||draft.dir!==dir)cleanDraft();try{const key={...draft.key,...patch};C.numeric(key);draft.key=key;draft.dirty=true;for(const f of [...C.fields,'interpolation'])if(f!==editingField)$('correction-'+f).value=key[f];$('correction-scale-slider').value=key.scalePercent;$('correction-revert').disabled=false;seamSignature='';app.render();}catch(e){app.status(e.message,true);}}
  function edit(fn,message){app.pause();try{store.commitCorrections(fn);signature='';draft=null;seamSignature='';app.status(message);}catch(e){app.status(e.message,true);}app.update();}
  for(const f of [...C.fields,'interpolation']){const editField=normalize=>{app.pause();const raw=$('correction-'+f).value;if(f!=='interpolation'&&!raw.trim()){if(normalize)app.status('Enter a correction value.',true);return;}patchDraft({[f]:f==='interpolation'?raw:Number(raw)},normalize?null:f);};$('correction-'+f).oninput=()=>editField(false);$('correction-'+f).onchange=()=>editField(true);}
  $('correction-scale-slider').oninput=()=>{app.pause();patchDraft({scalePercent:Number($('correction-scale-slider').value)});};
  $('correction-save').onclick=()=>edit(()=>C.upsert(p(),id(),current(),dir,draft.key),'Keyframe adjustment saved.');
  $('correction-delete').onclick=()=>edit(()=>{const t=C.own(p(),id(),dir);t.keys=t.keys.filter(k=>k.frame!==current());},'Correction key removed.');
  $('correction-reset').onclick=()=>edit(()=>{if(!C.frames(p(),id(),dir).length){delete p().corrections[id()].tracks[dir];dir='S';}else {C.own(p(),id(),dir);C.profile(p(),id()).tracks[dir]=C.empty();}},'This view’s keyframes cleared.');
  $('correction-revert').onclick=()=>{signature='';draft=null;seamSignature='';app.render();};
  $('correction-pivot').onclick=()=>{const g=SF.Placement.resolve(p(),id());patchDraft({pivotX:g.anchorX,pivotY:g.anchorY});};
  $('correction-enabled').onchange=()=>edit(()=>C.own(p(),id(),dir).enabled=$('correction-enabled').checked,'Saved corrections applied/bypassed.');
  $('correction-output').onchange=()=>edit(()=>{C.own(p(),id(),'S');C.profile(p(),id()).outputMode=$('correction-output').value;},'Correction output bounds updated.');
  const copyFront=()=>{const source=C.track(p(),id(),'S'),f=C.frames(p(),id(),dir);C.own(p(),id(),dir);C.profile(p(),id()).tracks[dir]={enabled:source.enabled,review:[],keys:source.keys.map(k=>({...k,name:f[k.frame].name,sha256:f[k.frame].sha256}))};};
  $('correction-copy').onclick=()=>edit(copyFront,'Front keys copied to this view.');
  $('correction-link').onchange=()=>edit(()=>{if($('correction-link').checked){C.own(p(),id(),dir);C.profile(p(),id()).tracks[dir]={...C.empty(),link:'S'};}else copyFront();},'View correction link updated.');
  $('correction-review').onclick=()=>edit(()=>{if(!C.frames(p(),id(),dir).length){delete p().corrections[id()].tracks[dir];dir='S';}else C.own(p(),id(),dir).review=[];},'Unmatched keys discarded. Undo restores them.');
  $('correction-view').onchange=()=>{dir=$('correction-view').value;previewSignature=id()+'|'+(C.frames(p(),id(),dir).length?dir:'S');signature='';draft=null;seamSignature='';app.pause();app.change({previewDirection:C.frames(p(),id(),dir).length?dir:'S',...(dir!=='S'&&p().settings.directionMode==='billboard'?{directionMode:'imported'}:{})});};
  $('correction-frame').onchange=()=>{const n=Number($('correction-frame').value);if(Number.isInteger(n)&&n>=0&&n<SF.Clips.get(p(),id()).frames.length)app.seekSource(n);else{app.status('Choose a whole source-frame index in this clip.',true);app.render();}};
  $('correction-list').onchange=()=>{if($('correction-list').value!=='')app.seekSource(Number($('correction-list').value));};
  for(const k of ['first','last'])$('correction-'+k).onclick=()=>app.seekSource(app.timing()[k==='first'?'rangeStart':'rangeEnd']);
  for(const k of ['original','corrected'])$('correction-'+k).onclick=()=>{p().preview.correctionView=k;store.touch();seamSignature='';app.render();};
  $('correction-details').ontoggle=()=>{seamSignature='';app.render();};
  function renderCorrection(clipId,index,view,factors){const sourceDir=C.direction(p(),clipId,view),live=draft?.dirty&&draft.id===clipId&&draft.index===index&&draft.dir===sourceDir?draft.key:null;return C.render(p(),clipId,index,view,factors,original(),live);}
  function beginDrag(e){if(!$('correction-drag').checked||$('correction-drag').disabled||SF.Studio.mode!=='workbench')return false;const g=SF.Renderer.correctionGeometry;if(!g||g.clipId!==id())return false;app.pause();if(!draft)cleanDraft();drag={x:e.clientX,y:e.clientY,key:{...draft.key},dirty:draft.dirty,factors:g.factors,recipe:g.recipe};$('preview').setPointerCapture(e.pointerId);return true;}
  function moveDrag(e){if(!drag)return false;const fx=drag.factors[0]*(drag.recipe?.widthFactor??1)*(drag.recipe?.mirror?-1:1);patchDraft({offsetX:Math.max(-8192,Math.min(8192,drag.key.offsetX+(e.clientX-drag.x)/fx)),offsetY:Math.max(-8192,Math.min(8192,drag.key.offsetY-(e.clientY-drag.y)/drag.factors[1]))});return true;}
  function endDrag(cancel=false){if(!drag)return false;if(cancel){patchDraft(drag.key);draft.dirty=drag.dirty;app.render();}drag=null;return true;}
  function seam(){const t=app.timing(),sig=JSON.stringify([id(),dir,t.rangeStart,t.rangeEnd,C.revision(p()),SF.Placement.resolve(p(),id()),p().settings.directionMode,original(),draft]);if(sig===seamSignature)return;seamSignature=sig;const c=$('correction-seam'),ctx=c.getContext('2d'),out=C.layout(p(),id(),false),g=SF.Placement.resolve(p(),id()),u=SF.Placement.metrics(p(),id()).unitsPerPixel,unit=175/Math.max(out.canvas[0]*u,out.canvas[1]*u,1),m=SF.Placement.metrics(p(),id(),unit);ctx.fillStyle='#1a130d';ctx.fillRect(0,0,c.width,c.height);
    [t.rangeStart,t.rangeEnd].forEach((index,i)=>{const x=i*c.width/2,w=c.width/2,view=SF.Directions.resolve(p(),id(),dir),f=view.frames[index],originX=x+(w-out.canvas[0]*u*unit)/2+out.anchor[0]*u*unit,originY=35+out.anchor[1]*u*unit;ctx.save();ctx.beginPath();ctx.rect(x,0,w,c.height);ctx.clip();ctx.fillStyle='#e7bc72';ctx.font='11px monospace';ctx.fillText(`${i?'Last':'First'} · source ${index}`,x+12,20);ctx.strokeStyle='#4f2b1b';ctx.beginPath();ctx.moveTo(x,originY);ctx.lineTo(x+w,originY);ctx.stroke();if(f)SF.Directions.draw(ctx,f,[g.anchorX,g.anchorY],originX,originY,m.factors,view.recipe,null,renderCorrection(id(),index,dir,m.factors));ctx.restore();});
  }
  $('correction-demo').onclick=()=>app.work(async(signal,progress)=>{const files=[];for(let i=0;i<12;i++){if(signal.cancelled)throw Error('Cancelled.');const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d'),q=1+i*.8/11,cx=180+i*130/11,feet=450-i*40/11;ctx.translate(cx,feet);ctx.scale(q,q);ctx.fillStyle='#e7bc72';ctx.fillRect(-30,-140,60,100);ctx.beginPath();ctx.arc(0,-164,24,0,Math.PI*2);ctx.fill();ctx.fillRect(-30,-40,22,40);ctx.fillRect(8,-40,22,40);ctx.fillStyle='#ec754f';ctx.fillRect(-65,-125,35,18);ctx.fillStyle='#4c8fea';ctx.fillRect(30,-110,35,18);const blob=await new Promise(r=>c.toBlob(r,'image/png'));files.push(new File([blob],`drift_${String(i+1).padStart(3,'0')}.png`,{type:'image/png'}));progress(`Making drift frame ${i+1}/12`);await SF.Media.tick();}
    const imported=await SF.Media.importFiles(files,signal,progress);app.stage(imported,result=>{if(!p().frames.length){store.replace({...p(),...result,settings:{...p().settings,clipId:'drift_demo',sourceFps:12,displayFps:12,rangeStart:0,rangeEnd:11,anchorX:256,anchorY:464}});SF.Studio.projectChanged();}else{let clipId='drift_demo',n=2;while(SF.Clips.ids(p()).includes(clipId))clipId='drift_demo_'+n++;const timing={...Object.fromEntries(SF.Clips.timingKeys.map(k=>[k,p().settings[k]])),sourceFps:12,displayFps:12,rangeStart:0,rangeEnd:11},candidate={...p(),extraClips:{...p().extraClips,[clipId]:{canvas:result.canvas,frames:result.frames,directions:{},timing}}};SF.Clips.checkBudget(candidate);p().extraClips=candidate.extraClips;SF.Placement.set(p(),clipId,{anchorX:256,anchorY:464,referenceCanvasHeightUnits:128,scalePercent:100,widthPercent:100,heightPercent:100,shapeLinked:true,offsetXUnits:0,offsetYUnits:0});store.touch();app.update();$('active-clip').value=clipId;$('active-clip').onchange();}SF.Clips.rebalance(p());app.status('Drift test loaded. Add first/last keys in Frame corrections.');});});
  const api={refresh,projectChanged,renderCorrection,beginDrag,moveDrag,endDrag};queueMicrotask(()=>{projectChanged();app.update();});return api;
})();
