// State-owned animation clocks. Visual actions never create damage or audio events.
SF.Playback = (() => {
  const policies=['continue','restart','once_return'],retriggers=['restart','ignore','queue'],attackStates=['hostile_attack','companion_combat'];
  const defaults=()=>({policy:'continue',returnClip:null,retrigger:'restart',marker:null});
  function initialize(p){p.statePlayback??={};p.playbackVersion=1;return p;}
  const binding=(p,state)=>({...defaults(),...(Object.hasOwn(p.statePlayback||{},state)?p.statePlayback[state]:{})});
  const assigned=(p,state)=>p.stateClips[state]||p.settings.clipId;
  function validate(p){initialize(p);if(typeof p.statePlayback!=='object'||Array.isArray(p.statePlayback))throw Error('Invalid state playback rules.');for(const [state,b]of Object.entries(p.statePlayback)){if(!SF.Simulator.states.includes(state)||!b||!policies.includes(b.policy)||!retriggers.includes(b.retrigger)||b.returnClip!==null&&!SF.Clips.ids(p).includes(b.returnClip))throw Error('Invalid state playback binding.');if(b.marker!==null){const m=b.marker;if(!m||!Number.isInteger(m.frame)||m.frame<0||m.frame>=2000||typeof m.name!=='string'||m.name.length>500||!/^([a-f0-9]{64})$/.test(m.sha256)||!SF.Clips.ids(p).includes(m.clipId))throw Error('Invalid visual strike marker.');}}return p;}
  function marker(p,state){const b=binding(p,state),m=b.marker,id=assigned(p,state),t=SF.Clips.timing(p,id),f=SF.Clips.get(p,id).frames[m?.frame];if(!m)return {enabled:false,reason:'none'};if(b.policy!=='once_return')return {enabled:false,reason:'rule_not_action',authored:m};if(m.clipId!==id||!f||f.sha256!==m.sha256||f.name!==m.name)return {enabled:false,reason:'source_changed',authored:m};if(m.frame<t.rangeStart||m.frame>t.rangeEnd)return {enabled:false,reason:'outside_range',authored:m};return {enabled:true,sourceFrame:m.frame,firstPassSeconds:(m.frame-t.rangeStart)/SF.Timeline.rate(t),informationalOnly:true,authored:m};}
  function setMarker(p,state,index){const id=assigned(p,state),f=SF.Clips.get(p,id).frames[index];if(!f)throw Error('Choose a source frame in the assigned animation.');return {clipId:id,frame:index,name:f.name,sha256:f.sha256};}
  function remapMarkers(p){initialize(p);for(const [state,b]of Object.entries(p.statePlayback)){const m=b.marker;if(!m)continue;const id=assigned(p,state);if(m.clipId!==id)continue;const frames=SF.Clips.get(p,id).frames;let matches=frames.map((f,i)=>f.sha256===m.sha256&&f.name===m.name?i:-1).filter(i=>i>=0);if(!matches.length)matches=frames.map((f,i)=>f.sha256===m.sha256?i:-1).filter(i=>i>=0);if(matches.length===1){const i=matches[0];b.marker={...m,frame:i,name:frames[i].name};}}}
  function create(){let state=null,entry=null,started=0,action=null,queued=false,serial=0,log=[];
    const record=(clock,message,type)=>{log.push({clock,message,type});if(log.length>24)log.shift();};
    function start(p,clock){const b=binding(p,state),id=assigned(p,state),timing=SF.Clips.timing(p,id);action={id,start:clock,end:clock+SF.Timeline.duration(timing),timing,binding:b,marker:marker(p,state),marked:false,serial:++serial};record(clock,`${id}: action started`,'start');}
    function enter(p,next,clock,token,preview=false){if(state===next&&entry===token)return false;if(action||queued)record(clock,'Action and queued replay cancelled on state exit.','cancel');state=next;entry=token;started=clock;action=null;queued=false;if(binding(p,state).policy==='once_return'&&(!attackStates.includes(state)||preview))start(p,clock);return true;}
    function tick(p,clock){let guard=0;while(action&&guard++<3){const a=action;if(a.marker.enabled&&!a.marked&&clock+1e-10>=a.start+a.marker.firstPassSeconds){a.marked=true;record(a.start+a.marker.firstPassSeconds,`Strike marker · source ${a.marker.sourceFrame}`,'marker');}if(clock+1e-10<a.end)break;const end=a.end;action=null;record(end,'Action finished; returned to ongoing animation.','finish');if(queued){queued=false;start(p,end);}else break;}}
    function trigger(p,clock){tick(p,clock);const b=binding(p,state);if(b.policy!=='once_return')return false;if(action){if(b.retrigger==='ignore'){record(clock,'Repeated trigger ignored.','ignore');return false;}if(b.retrigger==='queue'){if(!queued){queued=true;record(clock,'One replay queued.','queue');}return false;}record(clock,'Action restarted.','restart');}queued=false;start(p,clock);return true;}
    function snapshot(p,clock,globalElapsed){const b=binding(p,state),active=!!action,id=active?action.id:b.policy==='once_return'?(b.returnClip||p.settings.clipId):assigned(p,state),timing=active?action.timing:SF.Clips.timing(p,id),elapsed=active?Math.max(0,clock-action.start):b.policy==='restart'?Math.max(0,clock-started):Math.max(0,globalElapsed),frame=SF.Timeline.at(timing,elapsed);return {clipId:id,timing,elapsed,frame,phase:active?'action':b.policy==='once_return'?'return':'state',policy:b.policy,queued,serial:action?.serial||serial,markerReached:action?.marked||false,remainingSeconds:active?Math.max(0,action.end-clock):0};}
    function reset(p,next,clock,token,preview=false){state=null;entry=null;action=null;queued=false;log=[];serial=0;enter(p,next,clock,token,preview);}
    function seek(p,seconds,clock){const b=binding(p,state);if(action){const elapsed=Math.min(Math.max(0,seconds),SF.Timeline.duration(action.timing)-1e-9);action.start=clock-elapsed;action.end=action.start+SF.Timeline.duration(action.timing);action.marked=action.marker.enabled&&elapsed>=action.marker.firstPassSeconds;queued=false;return true;}if(b.policy==='restart'){started=clock-Math.max(0,seconds);return true;}return false;}
    return {enter,tick,trigger,snapshot,reset,seek,get log(){return log;}};
  }
  function contract(p){validate(p);return {version:1,legacyDefault:'continue',attackTrigger:'actual_simulator_attack_event',attackStates,actionCycle:'one_authored_cycle',returnPhase:'shared_global_phase',queueLimit:1,stateExit:'cancel_action_and_queue',audio:'forward_independent',damage:'simulator_only',bindings:Object.fromEntries(SF.Simulator.states.map(state=>{const b=binding(p,state),id=assigned(p,state),timing=SF.Clips.timing(p,id);return[state,{...b,clipId:id,effectiveReturnClip:b.returnClip||p.settings.clipId,cycleDurationSeconds:SF.Timeline.duration(timing),trigger:b.policy==='once_return'&&attackStates.includes(state)?'attack_event':'state_entry',strike:marker(p,state)}];}))};}
  return {policies,retriggers,attackStates,defaults,initialize,binding,assigned,validate,marker,setMarker,remapMarkers,create,contract};
})();
