SF.Studio = (() => {
  const $=id=>document.getElementById(id),app=SF.App,store=SF.Store,p=()=>store.project;
  let mode='workbench',activeClip=p().settings.clipId,galleryState='hostile',sim=SF.Simulator.create(p().simulation),accumulator=0,keys={},orbit=0,lastStrip='',lastSheet='',lastReadout=-1,previousState='',transition=null,lastAudioEvent=0,selectedTakeId=null,audioPast=[],audioFuture=[],compareClip=null,playback=SF.Playback?.create(),lastVisualEvent=0,playbackKey='';
  const currentState=()=>mode==='workbench'?'hostile':sim.model.state;
  const playbackClock=()=>sim.model.timeSeconds+Math.min(accumulator,1/60);
  const pose=()=>mode==='workbench'?null:playback?.snapshot(p(),playbackClock(),app.elapsed||0);
  const selectedClip=()=>mode==='workbench'&&SF.Clips.ids(p()).includes(activeClip)?activeClip:(pose()?.clipId||p().stateClips[currentState()]||p().settings.clipId);
  function resetPlayback(){playback?.reset(p(),sim.model.state,playbackClock(),sim.model.entryId,mode==='gallery');lastVisualEvent=sim.model.events.at(-1)?.id||0;playbackKey='';}
  function processVisualEvents(){playback?.enter(p(),sim.model.state,sim.model.timeSeconds,sim.model.entryId,mode==='gallery');playback?.tick(p(),sim.model.timeSeconds);for(const e of sim.model.events)if(e.id>lastVisualEvent){lastVisualEvent=e.id;if(e.type==='attack'&&e.state===sim.model.state&&e.entryId===sim.model.entryId)playback?.trigger(p(),e.timeSeconds);}}
  function options(node,items,selected){const signature=JSON.stringify(items);if(node.dataset.items!==signature){node.replaceChildren();for(const item of items){const o=document.createElement('option');o.value=item.value;o.textContent=item.label;node.append(o);}node.dataset.items=signature;}node.value=selected;}
  function directionButtons(){const dir=p().settings.previewDirection,has=p().frames.length>0,kinds=Object.fromEntries(SF.Directions.order.map(d=>{if(!has)return [d,'none'];const r=SF.Directions.resolve(p(),selectedClip(),d);return [d,d==='S'?'imported':r.kind==='imported'?(r.direction===d?'imported':'same'):r.kind];}));for(const id of ['direction-picker','quick-directions'])$(id).querySelectorAll('button').forEach(button=>(button.disabled=app.busy||!has,button.dataset.kind=kinds[button.dataset.direction]||'none',button.classList.toggle('selected',button.dataset.direction===dir)));}
  for(const id of ['direction-picker','quick-directions'])for(const dir of SF.Directions.order){const button=document.createElement('button');button.textContent=dir;button.dataset.direction=dir;button.title=SF.Directions.labels[dir];button.onclick=()=>{orbit=SF.Directions.order.indexOf(dir)*45;p().preview.orbitDegrees=orbit;$('orbit').value=orbit;$('orbit-value').textContent=orbit+'°';app.change({previewDirection:dir});};$(id).append(button);}
  options($('direction-import'),SF.Directions.order.filter(d=>d!=='S').map(d=>({value:d,label:`${d} · ${SF.Directions.labels[d]}`})),'SE');
  options($('audio-slot'),SF.Audio.slots.map(slot=>({value:slot,label:SF.Banks.labels[slot]})),'music_loop');
  options($('gallery-state'),SF.Simulator.states.map(state=>({value:state,label:SF.Simulator.labels[state]})),'hostile');
  function visual(){const state=currentState(),clipId=selectedClip(),direction=mode==='encounter'?SF.Directions.fromAngle(orbit-sim.model.facing):p().settings.previewDirection;
    return {mode,clipId,cameraOrbit:orbit,state,stateAge:mode==='workbench'?0:sim.model.stateAge,direction,model:sim.model};}
  $('source-facing').onchange=()=>{store.commitFacing(selectedClip(),$('source-facing').value);app.update();};
  function readout(){const m=sim.model;$('encounter-state').textContent=SF.Simulator.labels[m.state];$('inventory-count').textContent='Inventory '+(m.inventory?1:0);$('player-hp').value=m.player.hp;$('sprite-hp').value=m.actor.hp;$('player-health').textContent=m.player.hp;$('sprite-health').textContent=m.actor.hp;
    $('pickup').disabled=app.busy||!['defeat_transition','defeated'].includes(m.state);$('deploy').disabled=app.busy||m.state!=='stored';$('repack').disabled=app.busy||!['deploying','companion_combat','neutral_idle','neutral_roam'].includes(m.state);
    $('event-log').replaceChildren();for(const event of m.events.slice(-10)){const line=document.createElement('div');line.textContent=`${event.timeSeconds.toFixed(2)}s  ${event.message}`;$('event-log').append(line);}}
  const cue=()=>$('audio-slot').value;
  const resolvedBank=()=>SF.Banks.resolve(p(),cue());
  const selectedTake=()=>{const b=resolvedBank();return b?.takes.find(a=>a.id===selectedTakeId)||b?.takes[0]||null;};
  const bankKeys=['enabled','mode','selection','avoidLast','playOnEntry','firstDelay','gapMin','gapMax','maxPlays','seed','cooldown','retrigger','maxVoices'];
  const cueHelp={neutral_quips:'Quips share one session across idle and roaming. Combat, pickup and repack cancel them.',idle_loop:'Idle music or hum. Use Idle / roaming quips for spaced remarks.',roam_loop:'Background sound while roaming. Reuse Idle background to keep it running across idle/roam changes.',idle_entry:'Plays once per neutral session, then hands off to quips. A continuous entry loop keeps quips waiting.',defeat_sting:'Plays on defeat, then hands off to Defeated sound. If this sound loops continuously, it lasts until pickup.',release:'Deployment cue. The preview waits for the first delay and longest take; loops/repeats stop when deployment ends.',attack:'Triggered when the sprite lands an encounter attack; cooldown and retrigger rules apply.',hit:'Triggered when the sprite is hit; defeat takes priority on a fatal hit.',pickup:'On pickup. Repacking uses its own cue.',inventory:'Optional inventory sound; empty by default.'};
  function refreshAudio(){const slot=cue(),b=resolvedBank(),settings=b?.settings||SF.Banks.defaults(slot),linked=!!p().audioLinks[slot],a=selectedTake(),disabled=app.busy||!a||linked;
    selectedTakeId=a?.id||null;options($('audio-reference'),[{value:'',label:'This cue’s own takes'},...SF.Banks.slots.filter(s=>s!==slot).map(s=>({value:s,label:SF.Banks.labels[s]}))],p().audioLinks[slot]||'');$('audio-reference').disabled=app.busy;
    options($('audio-take'),b?.takes.length?b.takes.map((a,i)=>({value:a.id,label:`${i+1} · ${a.label}`})):[{value:'',label:'No takes · silent'}],selectedTakeId||'');$('audio-take').disabled=app.busy||!a;
    $('audio-cue-help').textContent=cueHelp[slot]||'Optional cue. Empty means silence; every take keeps its original audio.';
    for(const id of ['audio-remove','audio-replace','audio-label','audio-weight','audio-trimStart','audio-trimEnd','audio-loopStart','audio-loopEnd','audio-gainDb','audio-muted'])$(id).disabled=disabled;
    for(const id of ['audio-source','audio-converted'])$(id).disabled=app.busy||!a;
    $('import-audio').disabled=$('audio-demo').disabled=app.busy;$('audio-bank-test').disabled=app.busy||!SF.Banks.usable(b);
    const index=b?.takes.indexOf(a)??-1;$('audio-up').disabled=disabled||index<1;$('audio-down').disabled=disabled||index>=b.takes.length-1;
    $('audio-info').textContent=a?`${a.name} · ${a.buffer.duration.toFixed(3)}s · ${a.buffer.numberOfChannels}ch / ${a.buffer.sampleRate}Hz${linked?' · reference; edit the original cue':''}`:'No takes in this cue · silent.';
    $('audio-label').value=a?.label||'';$('audio-weight').value=a?.weight??1;
    for(const key of ['trimStart','trimEnd','loopStart','loopEnd','gainDb'])$('audio-'+key).value=a?a.edits[key].toFixed(key==='gainDb'?1:3):'';
    $('audio-muted').checked=a?.edits.muted||false;
    for(const key of bankKeys){const el=$('bank-'+key);el.disabled=app.busy||linked;if(el.type==='checkbox')el.checked=settings[key];else el.value=settings[key];}
    const periodic=['repeat','periodic'].includes(settings.mode);for(const key of ['gapMin','gapMax','maxPlays','playOnEntry'])$('bank-'+key).disabled=app.busy||linked||!periodic;
    $('bank-maxVoices').disabled=app.busy||linked||settings.retrigger!=='overlap';$('bank-avoidLast').disabled=app.busy||linked||settings.selection!=='random';
    $('bank-mode-help').textContent=settings.mode==='loop'?'One selected take loops continuously. Choose Periodic quips to vary takes.':settings.mode==='once'?'One take on entry/event. No automatic repeats.':'Takes play forward, with pauses independent of sprite FPS. Fades and crossfades come later.';
    const peak=a?a.peak*10**(a.edits.gainDb/20):0;$('audio-peak').textContent=a?`Mono peak ${peak?(20*Math.log10(peak)).toFixed(1):'−∞'} dBFS${peak>1?' · Reduce gain before export':''}`:'Peak —';$('audio-peak').classList.toggle('error',peak>1);
    $('audio-undo').disabled=app.busy||!audioPast.length;$('audio-redo').disabled=app.busy||!audioFuture.length;
    $('preview-volume').value=p().preview.volumePercent??70;$('volume-value').textContent=$('preview-volume').value+'%';SF.Audio.waveform($('waveform'),a);audioReadout();
  }
  function audioReadout(){const statuses=SF.Audio.bankStatus,voices=SF.Audio.activeVoices,clock=SF.Audio.clock;
    const lines=voices.map(v=>`${SF.Banks.labels[v.slot]||v.slot}: ${v.takeLabel||'WAV'}${v.loop?' · loop':''}`);
    for(const [key,s] of Object.entries(statuses))if(s.nextAt!==null&&!s.playing)lines.push(`${key==='audition_bank'?'Bank':'Cue'}: waiting ${Math.max(0,Math.ceil(s.nextAt-clock))}s · ${s.count} played`);
    const message=(SF.Audio.contextState==='suspended'&&SF.Audio.hasPlayback?'Paused. ':'')+(lines.join(' / ')||'Nothing playing.');if($('audio-bank-status').textContent!==message)$('audio-bank-status').textContent=message;
    $('audio-bank-pause').disabled=app.busy||!SF.Audio.previewActive;$('audio-bank-pause').textContent=SF.Audio.contextState==='suspended'?'Resume sounds':'Pause sounds';
    const history=Object.entries(statuses).flatMap(([key,s])=>s.log.map(x=>`${key} · ${x.time.toFixed(2)}s · ${x.message}`)).slice(-14).join('\n')||'No activity.';if($('audio-activity').textContent!==history)$('audio-activity').textContent=history;
  }
  function snapshotAudio(){return {audio:Object.fromEntries(Object.entries(p().audio).map(([key,b])=>[key,{...b,settings:{...b.settings},takes:b.takes.map(a=>({...a,edits:{...a.edits}}))}])),audioLinks:{...p().audioLinks}};}
  function trimAudioHistory(){while(audioPast.length>20)audioPast.shift();const active=new Set(SF.Banks.allTakes(p()).flatMap(a=>[a.buffer,a.blob]));const retiredBytes=()=>{const seen=new Set(active);let size=0;for(const h of [...audioPast,...audioFuture])for(const a of SF.Banks.allTakes(h))for(const obj of [a.buffer,a.blob])if(!seen.has(obj)){seen.add(obj);size+=obj instanceof Blob?obj.size:obj.length*obj.numberOfChannels*4;}return size;};while(retiredBytes()>64*1024*1024&&audioPast.length)audioPast.shift();while(retiredBytes()>64*1024*1024&&audioFuture.length)audioFuture.shift();}
  function editAudio(fn,message='Sound settings saved.'){let ok=false;const old=snapshotAudio();app.pause();SF.Audio.stop();try{fn();SF.Banks.validate(p());SF.Clips.checkBudget(p());audioPast.push(old);audioFuture=[];trimAudioHistory();store.touch();app.status(message);ok=true;}catch(e){Object.assign(p(),old);app.status(e.message,true);}app.update();return ok;}
  function ownBank(slot=cue()){return p().audio[slot]??=(SF.Banks.empty(slot));}
  function addTakes(slot,takes){return editAudio(()=>{const b=ownBank(slot);delete p().audioLinks[slot];for(const a of takes){a.id='take_'+b.nextTake++;a.label=a.name.slice(0,120);a.weight=1;a.edits.loop=b.settings.mode==='loop';b.takes.push(a);}selectedTakeId=takes.at(-1)?.id;},`${takes.length} take(s) added.`);}
  function processAudioEvents(){for(const e of sim.model.events)if(e.id>lastAudioEvent){lastAudioEvent=e.id;if(e.type)SF.Audio.event(p(),e.type);}}
  function refresh(){for(const id of ['active-clip','audio-slot','direction-import','orbit','preview-volume','new-clip-id',...['seed','roamRadius','moveSpeed','pauseMin','pauseMax','leashDistance'].map(k=>'sim-'+k)])$(id).disabled=app.busy;const id=selectedClip(),ids=SF.Clips.ids(p()),clip=SF.Clips.get(p(),id),has=p().frames.length>0;
    $('source-facing').value=SF.Directions.sourceFacing(p(),id);$('source-facing').disabled=app.busy||!has;$('source-facing-help').textContent=`Which way the original ${id} artwork faces. Left/Right flips it toward its target in the encounter (text and asymmetry flip too); everywhere else shows the original.`;
    options($('active-clip'),ids.map(value=>({value,label:value===p().settings.clipId?'Main clip':value})),id);
    $('active-clip').hidden=ids.length<2;$('clip-picker-label').hidden=ids.length<2;$('single-clip-label').hidden=ids.length>1;
    const editingState=mode==='encounter'?sim.model.state:galleryState;options($('state-clip'),[{value:'',label:`${p().settings.clipId} · main (fallback)`},...ids.map(value=>({value,label:value}))],p().stateClips[editingState]||'');
    $('gallery-state').disabled=app.busy||!has||mode==='encounter';$('state-clip').disabled=app.busy||!has||mode==='encounter';$('state-fallback').textContent=p().stateClips[editingState]?`Linked to ${p().stateClips[editingState]}.`:'Not linked · uses the main animation.';
    $('gallery-mode').classList.toggle('selected',mode!=='encounter');$('encounter-mode').classList.toggle('selected',mode==='encounter');$('gallery-state').value=editingState;
    const view=SF.Directions.resolve(p(),id,p().settings.previewDirection);$('view-label').textContent=`${p().settings.previewDirection} / ${SF.Directions.labels[p().settings.previewDirection]}`;
    $('view-kind').textContent=view.kind==='generated'?'APPROXIMATION':view.kind==='fallback'?'FRONT FALLBACK':p().settings.directionMode==='billboard'?'BILLBOARD':'IMPORTED';
    $('state-status').textContent=mode==='workbench'?'Tuning':mode==='encounter'?`Encounter · ${SF.Simulator.labels[sim.model.state]}`:`State · ${SF.Simulator.labels[sim.model.state]}`;
    const signature=id+'|'+clip.frames.map(f=>f.sha256).join(',');if(signature!==lastStrip){app.thumbs($('strip'),clip.frames,true);lastStrip=signature;}
    $('clip-context').textContent=!has?'Import your main animation in step 01 to begin.':id===p().settings.clipId?'Main animation · plays in every game state without its own animation.':'Extra animation · has its own timing, ground and size.';
    $('clip-label').textContent=has?(id===p().settings.clipId?id+' · main':id):'No sequence yet';$('media-summary').textContent=has?`${clip.frames.length} frames · ${SF.Clips.canvas(p(),id).join(' × ')} px`:'Image sequence';
    for(const key of ['seed','roamRadius','moveSpeed','pauseMin','pauseMax','leashDistance'])$('sim-'+key).value=p().simulation[key];
    const loaded=Object.keys(clip.directions||{}).length;$('direction-report').textContent=has?`${loaded+1} of 8 views use your own art. ${p().settings.directionMode==='generated'?'The rest are generated from the front.':p().settings.directionMode==='imported'?'Missing views show the front art.':'The front image faces every camera angle.'}`:'Import the main animation first.';
    for(const id of ['import-direction','contact-download','import-clip','gallery-mode','encounter-mode','attack','defeat-now','spawn-enemy','encounter-reset','defeat-audio-preview','release-audio-preview'])$(id).disabled=app.busy||!has;
    $('remove-clip').disabled=app.busy||id===p().settings.clipId;$('contact-zone').hidden=document.querySelector('[data-panel="directions"]').hidden||!$('sheet-drawer').open;
    directionButtons();refreshGround();refreshAudio();readout();SF.Steps?.refresh();SF.Roster?.refresh();afterRender(app.frame());
  }
  function refreshGround(){const id=selectedClip(),g=SF.Placement.resolve(p(),id),main=id===p().settings.clipId,has=p().frames.length>0;
    $('ground-clip').textContent=(main?id+' · main':id)+(has?' · '+g.canvas.join(' × ')+' px':' · no media');$('ground-inherit').checked=g.inherited;$('ground-inherit').disabled=app.busy||!has||main;
    $('ground-help').textContent=main?'Main animation. Extra animations set to use the main ground & size share these values.':g.inherited?'Uses the main animation\'s ground & size. Editing a value gives this animation its own.':'This animation has its own ground & size. Its ground point sits on the shared floor.';
    for(const key of SF.Placement.keys){const el=$(key);el.disabled=app.busy||!has;if(el.type==='checkbox')el.checked=g[key];else el.value=g[key];}
    $('anchorX').max=g.canvas[0];$('anchorY').max=g.canvas[1];$('scale-slider').value=g.scalePercent;$('scale-slider').disabled=app.busy||!has;for(const [id,k] of [['width-slider','widthPercent'],['height-slider','heightPercent']]){$(id).value=g[k];$(id).disabled=app.busy||!has;}for(const id of ['ground-normal','ground-wide','ground-tall'])$(id).disabled=app.busy||!has;
    $('ground-copy').disabled=app.busy||!has||main;$('ground-reset').disabled=app.busy||!has;$('ground-compare').disabled=app.busy||!has||(main&&!p().extraClips[compareClip]);$('ground-compare').textContent=main&&p().extraClips[compareClip]?'Back to '+compareClip:'Compare with main';
    const m=SF.Placement.metrics(p(),id);$('ground-size').textContent=!has?'Import an animation to set its ground and size.':`Entire image canvas at current size: ${m.widthUnits.toFixed(2)} × ${m.heightUnits.toFixed(2)} units. Offset Y is positive upward.`;
    if(!has){$('ground-output').textContent='';return;}
    try{const views=p().settings.directionMode==='billboard'?['S']:p().settings.directionMode==='generated'?SF.Directions.order:['S',...Object.keys(SF.Clips.get(p(),id).directions||{})],out=SF.Corrections.layout(p(),id);$('ground-output').textContent=`Output: ${out.canvas.join(' × ')} px · padded root ${out.anchor.map(v=>v.toFixed(2)).join(', ')}. Scale is applied once.`;$('ground-output').classList.remove('error');}catch(e){$('ground-output').textContent=e.message;$('ground-output').classList.add('error');}
  }
  for(const key of SF.Placement.keys)$(key).onchange=()=>app.change({[key]:$(key).type==='checkbox'?$(key).checked:Number($(key).value)});
  function groundEdit(patch,message){app.pause();try{store.commitPlacement(selectedClip(),patch);app.status(message);}catch(e){app.status(e.message,true);}lastSheet='';app.update();}
  for(const [id,patch] of [['ground-normal',{widthPercent:100,heightPercent:100,shapeLinked:true}],['ground-wide',{widthPercent:250,heightPercent:100,shapeLinked:false}],['ground-tall',{widthPercent:100,heightPercent:175,shapeLinked:false}]])$(id).onclick=()=>groundEdit(patch,'Clip shape updated.');
  $('ground-inherit').onchange=()=>groundEdit({inherit:$('ground-inherit').checked},'Clip placement updated.');
  $('ground-copy').onclick=()=>{const current=p().placements[selectedClip()];delete p().placements[selectedClip()];const inherited=SF.Placement.resolve(p(),selectedClip());if(current)p().placements[selectedClip()]=current;groundEdit({...Object.fromEntries(SF.Placement.keys.map(k=>[k,inherited[k]])),inherit:false},'Main placement copied to this clip.');};
  $('ground-reset').onclick=()=>groundEdit({...SF.Placement.defaults(p(),selectedClip()),inherit:false},'Clip placement reset from source bounds.');
  $('ground-compare').onclick=()=>{const id=selectedClip();if(id!==p().settings.clipId){compareClip=id;activeClip=p().settings.clipId;}else if(p().extraClips[compareClip])activeClip=compareClip;mode='workbench';app.pause();SF.Audio.stop();app.resetTimeline();app.update();};
  function afterRender(index){audioReadout();SF.ActionControls?.refresh();SF.Keyer?.refresh(index);if($('contact-zone').hidden)return;const id=selectedClip(),s=p().settings,signature=[id,index,JSON.stringify(SF.Placement.resolve(p(),id)),SF.Corrections.revision(p()),p().preview.correctionView,s.directionMode,s.generatedSideWidthPercent,s.rearDarknessPercent,s.mirrorDirections,Object.keys(SF.Clips.get(p(),id).directions||{}).join(',')].join('|');if(signature===lastSheet)return;lastSheet=signature;const sheet=SF.Directions.contactSheet(p(),id,index),c=$('contact-preview');c.getContext('2d').clearRect(0,0,c.width,c.height);c.getContext('2d').drawImage(sheet,0,0);}
  function projectChanged(){SF.Clips.initialize(p());selectedTakeId=null;audioPast=[];audioFuture=[];lastAudioEvent=0;compareClip=null;activeClip=p().settings.clipId;galleryState='hostile';mode='workbench';accumulator=0;keys={};sim=SF.Simulator.create(p().simulation);lastAudioEvent=0;orbit=p().preview.orbitDegrees||SF.Directions.order.indexOf(p().settings.previewDirection)*45;p().preview??={};SF.Audio.setVolume((p().preview.volumePercent??70)/100);lastStrip=lastSheet='';resetPlayback();SF.Keyer?.projectChanged();}
  function editTiming(patch){if(selectedClip()===p().settings.clipId||!Object.keys(patch).every(k=>SF.Clips.timingKeys.includes(k)))return false;Object.assign(SF.Clips.get(p(),selectedClip()).timing,patch);store.touch();return true;}
  $('active-clip').onchange=()=>{activeClip=$('active-clip').value;mode='workbench';SF.Audio.stop();app.pause();app.resetTimeline();app.update();};
  document.querySelectorAll('[data-tab]').forEach(button=>button.addEventListener('click',()=>{activeClip=selectedClip();const name=button.dataset.tab;if(name==='ground')p().settings.previewDirection='S';if(name==='states'){if(mode==='workbench'){mode='gallery';sim.gallery(galleryState);resetPlayback();SF.Audio.stop();app.pause();}}else mode='workbench';app.update();}));
  $('orbit').oninput=()=>{orbit=Number($('orbit').value);p().preview.orbitDegrees=orbit;$('orbit-value').textContent=orbit+'°';const raw=SF.Directions.fromAngle(orbit),center=SF.Directions.order.indexOf(p().settings.previewDirection)*45,delta=((orbit-center+540)%360)-180;if(Math.abs(delta)>27.5)p().settings.previewDirection=raw;store.touch();directionButtons();app.update();};
  $('import-direction').onclick=()=>$('direction-files').click();$('direction-files').onchange=()=>{const files=[...$('direction-files').files],dir=$('direction-import').value,id=selectedClip();$('direction-files').value='';if(!files.length)return;
    app.work(async(signal,progress)=>{const imported=await SF.Media.importFiles(files,signal,progress);if(imported.frames.length!==SF.Clips.get(p(),id).frames.length)throw Error(`${dir} has ${imported.frames.length} frames; ${id} expects ${SF.Clips.get(p(),id).frames.length}.`);if(imported.canvas.some((n,i)=>n>SF.Clips.canvas(p(),id)[i]))throw Error('Direction canvas exceeds this clip’s canvas. Pad/crop your source to its front canvas first.');
      app.stage(imported,result=>{const candidate={...p(),corrections:store.clone(p().corrections),directions:{...p().directions},extraClips:{...p().extraClips}};
        if(id===p().settings.clipId)candidate.directions[dir]={kind:'imported',frames:result.frames};else candidate.extraClips[id]={...candidate.extraClips[id],directions:{...candidate.extraClips[id].directions,[dir]:{kind:'imported',frames:result.frames}}};SF.Corrections.remap(candidate,id,dir);SF.Clips.checkBudget(candidate);Object.assign(p(),candidate);SF.Corrections.changed(p());SF.Clips.rebalance(p());store.touch();lastSheet='';});});};
  $('contact-download').onclick=async()=>{if(!p().frames.length)return;const sheet=SF.Directions.contactSheet(p(),selectedClip(),app.frame()),blob=await new Promise(r=>sheet.toBlob(r,'image/png'));SF.Pack.download(blob,p().settings.characterId+'_directions.png');};
  $('import-clip').onclick=()=>{const id=$('new-clip-id').value;if(!/^[a-z][a-z0-9_]{0,63}$/.test(id)||SF.Clips.ids(p()).includes(id)){app.status('Use a new animation ID: lower-case letters, digits and underscores. It must not already exist.',true);return;}$('clip-files').click();};
  $('clip-files').onchange=()=>{const files=[...$('clip-files').files],id=$('new-clip-id').value;$('clip-files').value='';if(!files.length)return;
    app.work(async(signal,progress)=>{const imported=await SF.Media.importFiles(files,signal,progress);app.stage(imported,result=>{if(SF.Clips.ids(p()).includes(id))throw Error('That clip ID already exists.');const timing=Object.fromEntries(SF.Clips.timingKeys.map(k=>[k,p().settings[k]]));timing.rangeStart=0;timing.rangeEnd=result.frames.length-1;const candidate={...p(),extraClips:{...p().extraClips,[id]:{canvas:result.canvas,frames:result.frames,timing,directions:{}}}};SF.Clips.checkBudget(candidate);p().extraClips=candidate.extraClips;activeClip=id;mode='workbench';SF.Clips.rebalance(p());store.touch();});});};
  $('remove-clip').onclick=()=>{const id=selectedClip();if(id===p().settings.clipId)return;delete p().extraClips[id];delete p().clipFacing[id];delete p().placements[id];delete p().corrections[id];for(const b of Object.values(p().statePlayback||{})){if(b.returnClip===id)b.returnClip=null;if(b.marker?.clipId===id)b.marker=null;}SF.Corrections.changed(p());for(const state of Object.keys(p().stateClips))if(p().stateClips[state]===id)delete p().stateClips[state];activeClip=p().settings.clipId;resetPlayback();store.touch();lastStrip='';app.update();};
  $('audio-slot').onchange=()=>{selectedTakeId=null;refreshAudio();};$('audio-take').onchange=()=>{selectedTakeId=$('audio-take').value;refreshAudio();};
  $('audio-reference').onchange=()=>editAudio(()=>{const ref=$('audio-reference').value;if(ref)p().audioLinks[cue()]=ref;else delete p().audioLinks[cue()];selectedTakeId=null;});
  $('import-audio').onclick=()=>$('audio-file').click();$('audio-file').onchange=()=>{const files=[...$('audio-file').files],slot=cue();$('audio-file').value='';if(!files.length)return;
    app.work(async(signal,progress)=>{if(files.length+(p().audio[slot]?.takes.length||0)>16||files.length+SF.Banks.allTakes(p()).length>64)throw Error('Up to 16 takes per cue and 64 per project.');const takes=[];for(const file of files){if(signal.cancelled)throw Error('Cancelled.');progress('Decoding '+file.name);takes.push(await SF.Audio.load(file));const candidate={...p(),audio:{...p().audio,[slot]:{...(p().audio[slot]||SF.Banks.empty(slot)),takes:[...(p().audio[slot]?.takes||[]),...takes.map((a,i)=>({...a,id:'take_'+((p().audio[slot]?.nextTake||1)+i),label:a.name.slice(0,120),weight:1}))],nextTake:(p().audio[slot]?.nextTake||1)+takes.length}}};SF.Clips.checkBudget(candidate);}if(signal.cancelled)throw Error('Cancelled.');addTakes(slot,takes);});};
  $('audio-replace').onclick=()=>$('audio-replace-file').click();$('audio-replace-file').onchange=()=>{const file=$('audio-replace-file').files[0],slot=cue(),id=selectedTakeId;$('audio-replace-file').value='';if(!file)return;app.work(async(signal,progress)=>{progress('Decoding replacement');const a=await SF.Audio.load(file);if(signal.cancelled)throw Error('Cancelled.');editAudio(()=>{const b=ownBank(slot),index=b.takes.findIndex(a=>a.id===id);if(index<0)throw Error('Take no longer exists.');const old=b.takes[index];a.edits.loop=b.settings.mode==='loop';b.takes[index]={...a,id:old.id,label:old.label===old.name.slice(0,120)?a.name.slice(0,120):old.label,weight:old.weight};},'Take replaced. Trim and gain reset.');});};
  $('audio-label').onchange=()=>editAudio(()=>selectedTake().label=$('audio-label').value.trim());$('audio-weight').onchange=()=>editAudio(()=>selectedTake().weight=Number($('audio-weight').value));
  for(const key of ['trimStart','trimEnd','loopStart','loopEnd','gainDb','muted'])$('audio-'+key).onchange=()=>editAudio(()=>{const a=selectedTake();a.edits[key]=key==='muted'?$('audio-'+key).checked:Number($('audio-'+key).value);if(['trimStart','trimEnd'].includes(key)){a.edits.loopStart=Math.max(a.edits.trimStart,a.edits.loopStart);a.edits.loopEnd=Math.min(a.edits.trimEnd,a.edits.loopEnd);}});
  for(const key of bankKeys)$('bank-'+key).onchange=()=>editAudio(()=>{const b=ownBank(),el=$('bank-'+key);b.settings[key]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value):el.value;if(key==='mode'){if(b.settings.mode!=='once')b.settings.retrigger='ignore';for(const a of b.takes)a.edits.loop=b.settings.mode==='loop';}});
  for(const [id,delta] of [['audio-up',-1],['audio-down',1]])$(id).onclick=()=>editAudio(()=>{const b=ownBank(),i=b.takes.findIndex(a=>a.id===selectedTakeId);[b.takes[i],b.takes[i+delta]]=[b.takes[i+delta],b.takes[i]];});
  $('audio-remove').onclick=()=>editAudio(()=>{const b=ownBank();b.takes=b.takes.filter(a=>a.id!==selectedTakeId);selectedTakeId=null;},'Take removed. Empty cue is silent.');
  for(const [id,redo] of [['audio-undo',false],['audio-redo',true]])$(id).onclick=()=>{const from=redo?audioFuture:audioPast,to=redo?audioPast:audioFuture;if(!from.length)return;app.pause();SF.Audio.stop();to.push(snapshotAudio());Object.assign(p(),from.pop());trimAudioHistory();selectedTakeId=null;store.touch();app.status(redo?'Audio edit restored.':'Audio edit undone.');app.update();};
  $('preview-volume').oninput=()=>{const value=Number($('preview-volume').value);p().preview.volumePercent=value;SF.Audio.setVolume(value/100);$('volume-value').textContent=value+'%';store.touch();};
  $('audio-source').onclick=()=>{app.pause();SF.Audio.audition(p(),cue(),selectedTakeId).catch(e=>app.status(e.message,true));};
  $('audio-converted').onclick=()=>app.work(async(signal,progress)=>{progress('Converting and auditioning PCM WAV…');const result=await SF.Audio.auditionConverted(SF.Banks.effective(selectedTake(),resolvedBank()),signal);app.status(`Auditioning WAV · 44.1 kHz mono PCM16 · ${result.metadata.sampleCount} samples.`);});
  $('audio-bank-test').onclick=()=>{app.pause();SF.Audio.auditionBank(p(),cue()).then(()=>{audioReadout();app.status('Testing this cue. Pause or Stop audio to end it.');}).catch(e=>app.status(e.message,true));};
  $('audio-bank-pause').onclick=()=>{(SF.Audio.contextState==='suspended'?SF.Audio.resume():SF.Audio.pause()).then(audioReadout).catch(e=>app.status(e.message,true));};
  $('audio-stop').onclick=()=>{app.pause();SF.Audio.stop();audioReadout();};
  $('audio-demo').onclick=()=>app.work(async(signal,progress)=>{const takes=[];for(const [i,freq] of [155,220].entries()){const length=Math.round(44100*(i?.65:.45)),samples=new Float32Array(length);for(let n=0;n<length;n++){const t=n/44100,envelope=Math.min(1,n/800,(length-1-n)/1200);samples[n]=.22*envelope*(Math.sin(2*Math.PI*freq*t)+.25*Math.sin(4*Math.PI*freq*t));}progress('Making test tone '+(i+1));takes.push(await SF.Audio.load(new File([SF.Audio.writeWav(samples)],`test_tone_${i+1}.wav`,{type:'audio/wav'})));}if(signal.cancelled)throw Error('Cancelled.');$('audio-slot').value='neutral_quips';if(!addTakes('neutral_quips',takes))return;editAudio(()=>{const s=ownBank('neutral_quips').settings;Object.assign(s,{enabled:true,mode:'periodic',selection:'random',avoidLast:true,playOnEntry:true,firstDelay:0,gapMin:1,gapMax:2,maxPlays:0});},'Two synthetic tones added. Click Test this cue, or check Neutral idle in Field test.');app.tab('audio');});
  function gallery(next,autoPlay=false){mode='gallery';galleryState=next;sim.gallery(next);resetPlayback();SF.Audio.stop();app.pause();app.resetTimeline();app.tab('states');app.update();if(autoPlay&&!app.playing&&p().frames.length)$('play').click();}
  $('gallery-state').onchange=()=>{transition=null;gallery($('gallery-state').value);};$('gallery-mode').onclick=()=>gallery(galleryState);
  $('state-clip').onchange=()=>{app.pause();const id=$('state-clip').value;const edit=()=>{if(id)p().stateClips[galleryState]=id;else delete p().stateClips[galleryState];if(p().statePlayback?.[galleryState])p().statePlayback[galleryState].marker=null;};if(SF.Playback)store.commitPlayback(edit);else{edit();store.touch();}app.resetTimeline();resetPlayback();app.update();};
  $('encounter-mode').onclick=()=>{if(!p().frames.length)return;mode='encounter';sim=SF.Simulator.create(p().simulation);lastAudioEvent=0;accumulator=0;keys={};resetPlayback();SF.Audio.stop();app.pause();app.tab('states');app.update();$('play').click();};
  $('defeat-audio-preview').onclick=()=>{transition='defeat';gallery('defeat_transition',true);};$('release-audio-preview').onclick=()=>{transition='release';gallery('deploying',true);};
  for(const [button,method] of Object.entries({attack:'attack','defeat-now':'defeat',pickup:'pickup',deploy:'deploy','spawn-enemy':'spawn',repack:'repack'}))$(button).onclick=()=>{if(mode!=='encounter'){mode='encounter';app.tab('states');}sim[method]();processVisualEvents();if(!app.playing)SF.Audio.stop();SF.Audio.sync(p(),sim.model.state,sim.model.stateAge,app.playing);if(app.playing)processAudioEvents();app.update();};
  $('pause-all').onclick=()=>{app.pause();SF.Audio.pause().catch(()=>{});};$('encounter-reset').onclick=()=>{app.pause();SF.Audio.stop();sim=SF.Simulator.create(p().simulation);lastAudioEvent=0;mode='encounter';accumulator=0;keys={};resetPlayback();app.update();};
  for(const key of ['seed','roamRadius','moveSpeed','pauseMin','pauseMax','leashDistance'])$('sim-'+key).onchange=()=>{const config={...p().simulation,[key]:Number($('sim-'+key).value)};try{SF.Simulator.validate(config);p().simulation=config;store.touch();app.pause();SF.Audio.stop();sim=SF.Simulator.create(config);lastAudioEvent=0;accumulator=0;resetPlayback();app.status('Roaming settings saved. Encounter reset.');}catch(e){app.status(e.message,true);}app.update();};
  function advance(delta){accumulator+=Math.max(0,delta);let steps=0;const sting=SF.Audio.cueDuration(p(),'defeat_sting'),release=SF.Audio.cueDuration(p(),'release');
    while(accumulator>=1/60&&steps<300){sim.step(1/60,keys,mode==='encounter',sting,release);if(mode!=='workbench')processVisualEvents();accumulator-=1/60;steps++;}
    if(mode!=='workbench')playback?.tick(p(),playbackClock());
    if(transition==='release'&&sim.model.state==='deploying'&&sim.model.stateAge>Math.max(.7,release)){galleryState='companion_combat';sim.gallery('companion_combat');resetPlayback();transition=null;}
    const state=currentState();SF.Audio.sync(p(),state,sim.model.stateAge,true);processAudioEvents();SF.Audio.position(sim.model.actor,sim.model.player,orbit);
    const v=pose(),key=[state,sim.model.entryId,v?.clipId,v?.phase,v?.serial].join('|');if(previousState!==state||key!==playbackKey){previousState=state;playbackKey=key;app.update();}else if(Math.floor(sim.model.timeSeconds*5)!==lastReadout){lastReadout=Math.floor(sim.model.timeSeconds*5);readout();$('state-status').textContent=mode==='encounter'?`Encounter · ${SF.Simulator.labels[state]}`:mode==='gallery'?`State · ${SF.Simulator.labels[state]}`:'Tuning';}
  }
  function place(event){if(mode!=='encounter'||sim.model.state!=='stored')return;const box=$('preview').getBoundingClientRect(),g=SF.Renderer.sceneGeometry;if(!g)return;if(!app.playing)SF.Audio.stop();sim.deploy({x:(event.clientX-box.left-g.ox)/g.unit,z:(event.clientY-box.top-g.oy)/(g.unit*.6)});processVisualEvents();SF.Audio.sync(p(),sim.model.state,0,app.playing);app.update();}
  document.addEventListener('keydown',event=>{if(mode!=='encounter'||['INPUT','SELECT','TEXTAREA'].includes(event.target.tagName))return;const key=event.key.toLowerCase();if(['w','a','s','d','arrowleft','arrowright','arrowup','arrowdown'].includes(key)){event.preventDefault();keys[event.key.startsWith('Arrow')?event.key:key]=true;}});
  document.addEventListener('keyup',event=>{keys[event.key]=false;keys[event.key.toLowerCase()]=false;});window.addEventListener('blur',()=>keys={});
  p().preview??={};
  const api={pose,resetPlayback,seek:seconds=>mode!=='workbench'&&playback?.seek(p(),seconds,playbackClock()),rewind:()=>resetPlayback(),testAction(){app.clearManual?.();if(mode==='workbench'){gallery(galleryState);return;}if(SF.Playback?.binding(p(),sim.model.state).policy==='once_return')playback?.trigger(p(),playbackClock());else gallery(galleryState);app.update();},inspect:state=>gallery(state),get playbackLog(){return playback?.log||[];},get bindingState(){return mode==='encounter'?sim.model.state:galleryState;},renderCorrection:(...a)=>SF.Keyer?.renderCorrection(...a),beginCorrectionDrag:e=>SF.Keyer?.beginDrag(e),moveCorrectionDrag:e=>SF.Keyer?.moveDrag(e),endCorrectionDrag:cancel=>SF.Keyer?.endDrag(cancel),visual,refresh,afterRender,projectChanged,editTiming,advance,place,get mode(){return mode;},get clipId(){return selectedClip();},get simulation(){return sim;}};
  queueMicrotask(()=>{SF.Studio=api;projectChanged();app.update();});return api;
})();
